export const WARNING_STRING_KEYS = {
  // Onboarding
  ALWAYS_VERIFY_URL: 'WARNINGS.ONBOARDING.ALWAYS_VERIFY_URL',

  // Trade Box
  LIMIT_PRICE_TRIGGER_PRICE_SLIPPAGE_HIGHER:
    'WARNINGS.TRADE_BOX.LIMIT_PRICE_TRIGGER_PRICE_SLIPPAGE_HIGHER',
  LIMIT_PRICE_TRIGGER_PRICE_SLIPPAGE_LOWER:
    'WARNINGS.TRADE_BOX.LIMIT_PRICE_TRIGGER_PRICE_SLIPPAGE_LOWER',
  MARKET_ORDER_CLOSE_TO_MAX_LEVERAGE: 'WARNINGS.TRADE_BOX.MARKET_ORDER_CLOSE_TO_MAX_LEVERAGE',
  MARKET_ORDER_WARNING_INDEX_PRICE_SLIPPAGE:
    'WARNINGS.TRADE_BOX.MARKET_ORDER_WARNING_INDEX_PRICE_SLIPPAGE',
  MARKET_ORDER_WARNING_ORDERBOOK_SLIPPAGE:
    'WARNINGS.TRADE_BOX.MARKET_ORDER_WARNING_ORDERBOOK_SLIPPAGE',
  MARKET_STATUS_CLOSE_ONLY: 'WARNINGS.TRADE_BOX.MARKET_STATUS_CLOSE_ONLY',
  STOP_MARKET_ORDER_MAY_NOT_EXECUTE: 'WARNINGS.TRADE_BOX.STOP_MARKET_ORDER_MAY_NOT_EXECUTE',
  TAKE_PROFIT_MARKET_ORDER_MAY_NOT_EXECUTE:
    'WARNINGS.TRADE_BOX.TAKE_PROFIT_MARKET_ORDER_MAY_NOT_EXECUTE',
};
