export const DEFAULT_AFFILIATES_EARN_PER_MONTH_USD = 3000;
export const DEFAULT_AFFILIATES_VIP_EARN_PER_MONTH_USD = 10000;

export const AFFILIATES_FEE_DISCOUNT_USD = 500;
export const AFFILIATES_REQUIRED_VOLUME_USD = 10_000;

export const REF_SHARE_VOLUME_CAP_USD = 50_000_000;
export const DEFAULT_TAKER_3_FEE = 0.0004;
export const MAX_AFFILIATE_VIP_SHARE = 0.5;
export const DEFAULT_MAX_AFFILIATE_SHARE = 0.15;
