export const DEFAULT_AFFILIATES_EARN_PER_MONTH = 3000;
export const DEFAULT_AFFILIATES_VIP_EARN_PER_MONTH = 10000;

export const AFFILIATES_FEE_DISCOUNT = 500;

export const REF_SHARE_VOLUME_CAP = 50_000_000;
export const DEFAULT_TAKER_3_FEE = 0.0004;
export const MAX_AFFILIATE_VIP_SHARE = 0.5;
export const DEFAULT_MAX_AFFILIATE_SHARE = 0.15;
