export enum DialogTypes {
  AdjustIsolatedMargin = 'AdjustIsolatedMargin',
  AdjustTargetLeverage = 'AdjustTargetLeverage',
  ClosePosition = 'ClosePosition',
  Deposit = 'Deposit',
  DisconnectWallet = 'DisconnectWallet',
  DisplaySettings = 'DisplaySettings',
  ExchangeOffline = 'ExchangeOffline',
  ExternalLink = 'ExternalLink',
  ExternalNavStride = 'ExternalNavStride',
  FillDetails = 'FillDetails',
  Help = 'Help',
  ExternalNavKeplr = 'ExternalNavKeplr',
  ManageFunds = 'ManageFunds',
  MnemonicExport = 'MnemonicExport',
  MobileDownload = 'MobileDownload',
  MobileSignIn = 'MobileSignIn',
  NewMarketAgreement = 'NewMarketAgreement',
  NewMarketMessageDetails = 'NewMarketMessageDetails',
  Onboarding = 'Onboarding',
  OrderDetails = 'OrderDetails',
  Preferences = 'Preferences',
  RateLimit = 'RateLimit',
  RestrictedGeo = 'RestrictedGeo',
  RestrictedWallet = 'RestrictedWallet',
  SelectMarginMode = 'SelectMarginMode',
  Trade = 'Trade',
  Transfer = 'Transfer',
  Withdraw = 'Withdraw',
  WithdrawalGated = 'WithdrawalGated',
}

export enum TradeBoxDialogTypes {
  ClosePosition = 'ClosePosition',
  SelectMarginMode = 'SelectMarginMode',
}
