export enum CountryCodes {
  AD = 'AD',
  AE = 'AE',
  AF = 'AF',
  AG = 'AG',
  AI = 'AI',
  AL = 'AL',
  AM = 'AM',
  AO = 'AO',
  AQ = 'AQ',
  AR = 'AR',
  AS = 'AS',
  AT = 'AT',
  AU = 'AU',
  AW = 'AW',
  AZ = 'AZ',
  BA = 'BA',
  BB = 'BB',
  BD = 'BD',
  BE = 'BE',
  BF = 'BF',
  BG = 'BG',
  BH = 'BH',
  BI = 'BI',
  BJ = 'BJ',
  BL = 'BL',
  BM = 'BM',
  BN = 'BN',
  BO = 'BO',
  BR = 'BR',
  BS = 'BS',
  BT = 'BT',
  BV = 'BV',
  BW = 'BW',
  BY = 'BY',
  BZ = 'BZ',
  CA = 'CA',
  CC = 'CC',
  CD = 'CD',
  CF = 'CF',
  CG = 'CG',
  CH = 'CH',
  CI = 'CI',
  CK = 'CK',
  CL = 'CL',
  CM = 'CM',
  CN = 'CN',
  CO = 'CO',
  CR = 'CR',
  CU = 'CU',
  CV = 'CV',
  CW = 'CW',
  CX = 'CX',
  CY = 'CY',
  CZ = 'CZ',
  DE = 'DE',
  DJ = 'DJ',
  DK = 'DK',
  DM = 'DM',
  DO = 'DO',
  DZ = 'DZ',
  EC = 'EC',
  EE = 'EE',
  EG = 'EG',
  EH = 'EH',
  ER = 'ER',
  ES = 'ES',
  ET = 'ET',
  FI = 'FI',
  FJ = 'FJ',
  FK = 'FK',
  FM = 'FM',
  FO = 'FO',
  FR = 'FR',
  GA = 'GA',
  GB = 'GB',
  GD = 'GD',
  GE = 'GE',
  GG = 'GG',
  GH = 'GH',
  GI = 'GI',
  GL = 'GL',
  GM = 'GM',
  GN = 'GN',
  GQ = 'GQ',
  GR = 'GR',
  GS = 'GS',
  GT = 'GT',
  GU = 'GU',
  GW = 'GW',
  GY = 'GY',
  HK = 'HK',
  HM = 'HM',
  HN = 'HN',
  HR = 'HR',
  HT = 'HT',
  HU = 'HU',
  ID = 'ID',
  IE = 'IE',
  IL = 'IL',
  IM = 'IM',
  IN = 'IN',
  IO = 'IO',
  IQ = 'IQ',
  IR = 'IR',
  IS = 'IS',
  IT = 'IT',
  JE = 'JE',
  JM = 'JM',
  JO = 'JO',
  JP = 'JP',
  KE = 'KE',
  KG = 'KG',
  KH = 'KH',
  KI = 'KI',
  KM = 'KM',
  KN = 'KN',
  KP = 'KP',
  KR = 'KR',
  KW = 'KW',
  KY = 'KY',
  KZ = 'KZ',
  LA = 'LA',
  LB = 'LB',
  LC = 'LC',
  LI = 'LI',
  LK = 'LK',
  LR = 'LR',
  LS = 'LS',
  LT = 'LT',
  LU = 'LU',
  LV = 'LV',
  LY = 'LY',
  MA = 'MA',
  MC = 'MC',
  MD = 'MD',
  ME = 'ME',
  MF = 'MF',
  MG = 'MG',
  MH = 'MH',
  MK = 'MK',
  ML = 'ML',
  MM = 'MM',
  MN = 'MN',
  MO = 'MO',
  MP = 'MP',
  MR = 'MR',
  MS = 'MS',
  MT = 'MT',
  MU = 'MU',
  MV = 'MV',
  MW = 'MW',
  MX = 'MX',
  MY = 'MY',
  MZ = 'MZ',
  NA = 'NA',
  NC = 'NC',
  NE = 'NE',
  NF = 'NF',
  NG = 'NG',
  NI = 'NI',
  NL = 'NL',
  NO = 'NO',
  NP = 'NP',
  NR = 'NR',
  NU = 'NU',
  NZ = 'NZ',
  OM = 'OM',
  PA = 'PA',
  PE = 'PE',
  PF = 'PF',
  PG = 'PG',
  PH = 'PH',
  PK = 'PK',
  PL = 'PL',
  PM = 'PM',
  PN = 'PN',
  PR = 'PR',
  PT = 'PT',
  PW = 'PW',
  PY = 'PY',
  QA = 'QA',
  RO = 'RO',
  RS = 'RS',
  RU = 'RU',
  RW = 'RW',
  SA = 'SA',
  SB = 'SB',
  SC = 'SC',
  SD = 'SD',
  SE = 'SE',
  SG = 'SG',
  SH = 'SH',
  SI = 'SI',
  SJ = 'SJ',
  SK = 'SK',
  SL = 'SL',
  SM = 'SM',
  SN = 'SN',
  SO = 'SO',
  SR = 'SR',
  SS = 'SS',
  ST = 'ST',
  SV = 'SV',
  SX = 'SX',
  SY = 'SY',
  SZ = 'SZ',
  TC = 'TC',
  TD = 'TD',
  TF = 'TF',
  TG = 'TG',
  TH = 'TH',
  TJ = 'TJ',
  TK = 'TK',
  TL = 'TL',
  TM = 'TM',
  TN = 'TN',
  TO = 'TO',
  TR = 'TR',
  TT = 'TT',
  TV = 'TV',
  TW = 'TW',
  TZ = 'TZ',
  UA = 'UA',
  UG = 'UG',
  UM = 'UM',
  US = 'US',
  UY = 'UY',
  UZ = 'UZ',
  VA = 'VA',
  VC = 'VC',
  VE = 'VE',
  VG = 'VG',
  VI = 'VI',
  VN = 'VN',
  VU = 'VU',
  WF = 'WF',
  WS = 'WS',
  XK = 'XK',
  YE = 'YE',
  ZA = 'ZA',
  ZM = 'ZM',
  ZW = 'ZW',
}

export const RESTRICTED_COUNTRIES = {
  USA: CountryCodes.US,
  CANADA: CountryCodes.CA,

  // OFAC Sanctioned
  AFGHANISTAN: CountryCodes.AF,
  BELARUS: CountryCodes.BY,
  CENTRAL_AFRICAN_REPUBLIC: CountryCodes.CF,
  CUBA: CountryCodes.CU,
  DEM_REPUBLIC_CONGO: CountryCodes.CD, // Democratic Republic of Congo
  ERITREA: CountryCodes.ER, // Eritrea
  IRAN: CountryCodes.IR,
  IRAQ: CountryCodes.IQ,
  IVORY_COAST: CountryCodes.CI, // Cote D'Ivoire
  LEBANON: CountryCodes.LB,
  LIBERIA: CountryCodes.LR,
  LIBYA: CountryCodes.LY,
  MALI: CountryCodes.ML,
  MYANMAR: CountryCodes.MM, // Burma
  NICARAGUA: CountryCodes.NI,
  NORTH_KOREA: CountryCodes.KP, // Democratic People's Republic of Korea
  SOMALIA: CountryCodes.SO,
  SOUTH_SUDAN: CountryCodes.SS,
  SUDAN: CountryCodes.SD, // The Republic of the Sudan
  SYRIA: CountryCodes.SY, // The Syrian Arab Republic
  VENEZUELA: CountryCodes.VE,
  ZIMBABWE: CountryCodes.ZW,
};

export const SOFT_BLOCKED_COUNTRIES = [];

export const BLOCKED_COUNTRIES = [RESTRICTED_COUNTRIES.USA, RESTRICTED_COUNTRIES.CANADA];

export const OFAC_SANCTIONED_COUNTRIES = [
  RESTRICTED_COUNTRIES.AFGHANISTAN,
  RESTRICTED_COUNTRIES.BELARUS,
  RESTRICTED_COUNTRIES.CENTRAL_AFRICAN_REPUBLIC,
  RESTRICTED_COUNTRIES.CUBA,
  RESTRICTED_COUNTRIES.DEM_REPUBLIC_CONGO,
  RESTRICTED_COUNTRIES.ERITREA,
  RESTRICTED_COUNTRIES.IRAN,
  RESTRICTED_COUNTRIES.IRAQ,
  RESTRICTED_COUNTRIES.IVORY_COAST,
  RESTRICTED_COUNTRIES.LEBANON,
  RESTRICTED_COUNTRIES.LIBERIA,
  RESTRICTED_COUNTRIES.LIBYA,
  RESTRICTED_COUNTRIES.MALI,
  RESTRICTED_COUNTRIES.MYANMAR,
  RESTRICTED_COUNTRIES.NICARAGUA,
  RESTRICTED_COUNTRIES.NORTH_KOREA,
  RESTRICTED_COUNTRIES.SOMALIA,
  RESTRICTED_COUNTRIES.SOUTH_SUDAN,
  RESTRICTED_COUNTRIES.SUDAN,
  RESTRICTED_COUNTRIES.SYRIA,
  RESTRICTED_COUNTRIES.VENEZUELA,
  RESTRICTED_COUNTRIES.ZIMBABWE,
];

export const COUNTRIES_MAP: { [country: string]: string } = {
  'Afghanistan (‫افغانستان‬‎)': CountryCodes.AF,
  Akrotiri: CountryCodes.GB,
  'Albania (Shqipëri)': CountryCodes.AL,
  'Algeria (‫الجزائر‬‎)': CountryCodes.DZ,
  'American Samoa': CountryCodes.AS,
  Andorra: CountryCodes.AD,
  Angola: CountryCodes.AO,
  Anguilla: CountryCodes.AI,
  Antarctica: CountryCodes.AQ,
  'Antigua & Barbuda': CountryCodes.AG,
  Argentina: CountryCodes.AR,
  'Armenia (Հայաստան)': CountryCodes.AM,
  Aruba: CountryCodes.AW,
  'Ashmore and Cartier Islands': CountryCodes.AU,
  Australia: CountryCodes.AU,
  'Austria (Österreich)': CountryCodes.AT,
  'Azerbaijan (Azərbaycan)': CountryCodes.AZ,
  Bahamas: CountryCodes.BS,
  'Bahrain (‫البحرين‬‎)': CountryCodes.BH,
  'Baker Island': CountryCodes.UM,
  'Bangladesh (বাংলাদেশ)': CountryCodes.BD,
  Barbados: CountryCodes.BB,
  Belarus: CountryCodes.BY,
  'Belgium (België)': CountryCodes.BE,
  Belize: CountryCodes.BZ,
  'Benin (Bénin)': CountryCodes.BJ,
  Bermuda: CountryCodes.BM,
  'Bhutan (འབྲུག)': CountryCodes.BT,
  Bolivia: CountryCodes.BO,
  'Bosnia-Herzegovina (Босна и Херцеговина)': CountryCodes.BA,
  Botswana: CountryCodes.BW,
  'Bouvet Island': CountryCodes.BV,
  'Brazil (Brasil)': CountryCodes.BR,
  'British Indian Ocean Territory': CountryCodes.IO,
  'British Virgin Islands': CountryCodes.VG,
  Brunei: CountryCodes.BN,
  'Bulgaria (България)': CountryCodes.BG,
  'Burkina Faso': CountryCodes.BF,
  Burma: CountryCodes.MM,
  'Burundi (Uburundi)': CountryCodes.BI,
  'Cambodia (កម្ពុជា)': CountryCodes.KH,
  'Cameroon (Cameroun)': CountryCodes.CM,
  Canada: CountryCodes.CA,
  'Cape Verde (Kabu Verdi)': CountryCodes.CV,
  'Cayman Islands': CountryCodes.KY,
  'Central African Republic (République centrafricaine)': CountryCodes.CF,
  'Chad (Tchad)': CountryCodes.TD,
  Chile: CountryCodes.CL,
  'China (中国)': CountryCodes.CN,
  'Christmas Island': CountryCodes.CX,
  'Clipperton Island': CountryCodes.FR,
  'Cocos (Keeling) Islands': CountryCodes.CC,
  Colombia: CountryCodes.CO,
  'Comoros (‫جزر القمر‬‎)': CountryCodes.KM,
  'Congo (Brazzaville)': CountryCodes.CG,
  'Congo (Kinshasa)': CountryCodes.CD,
  'Cook Islands': CountryCodes.CK,
  'Coral Sea Islands': CountryCodes.AU,
  'Costa Rica': CountryCodes.CR,
  "Cote D'Ivoire (Ivory Coast)": CountryCodes.CI,
  'Croatia (Hrvatska)': CountryCodes.HR,
  Cuba: CountryCodes.CU,
  Curacao: CountryCodes.CW,
  'Cyprus (Κύπρος)': CountryCodes.CY,
  'Czech Republic (Česká republika)': CountryCodes.CZ,
  'Denmark (Danmark)': CountryCodes.DK,
  Dhekelia: CountryCodes.GB,
  Djibouti: CountryCodes.DJ,
  Dominica: CountryCodes.DM,
  'Dominican Republic (República Dominicana)': CountryCodes.DO,
  'East Timor': CountryCodes.TL,
  Ecuador: CountryCodes.EC,
  'Egypt (‫مصر‬‎)': CountryCodes.EG,
  'El Salvador': CountryCodes.SV,
  'Equatorial Guinea (Guinea Ecuatorial)': CountryCodes.GQ,
  Eritrea: CountryCodes.ER,
  'Estonia (Eesti)': CountryCodes.EE,
  Ethiopia: CountryCodes.ET,
  'Falkland Islands (Islas Malvinas)': CountryCodes.FK,
  'Faroe Islands (Føroyar)': CountryCodes.FO,
  'Federated States of Micronesia': CountryCodes.FM,
  Fiji: CountryCodes.FJ,
  'Finland (Suomi)': CountryCodes.FI,
  France: CountryCodes.FR,
  'French Polynesia (Polynésie française)': CountryCodes.PF,
  'French Southern and Antarctic Lands': CountryCodes.TF,
  Gabon: CountryCodes.GA,
  'The Gambia': CountryCodes.GM,
  'Georgia (საქართველო)': CountryCodes.GE,
  'Germany (Deutschland)': CountryCodes.DE,
  'Ghana (Gaana)': CountryCodes.GH,
  Gibraltar: CountryCodes.GI,
  'Greece (Ελλάδα)': CountryCodes.GR,
  'Greenland (Kalaallit Nunaat)': CountryCodes.GL,
  Grenada: CountryCodes.GD,
  Guam: CountryCodes.GU,
  Guatemala: CountryCodes.GT,
  Guernsey: CountryCodes.GG,
  'Guinea (Guinée)': CountryCodes.GN,
  'Guinea-Bissau (Guiné Bissau)': CountryCodes.GW,
  Guyana: CountryCodes.GY,
  Haiti: CountryCodes.HT,
  'Heard Island and McDonald Islands': CountryCodes.HM,
  'Holy See': CountryCodes.VA,
  Honduras: CountryCodes.HN,
  'Hong Kong (香港)': CountryCodes.HK,
  'Howland Island': CountryCodes.UM,
  'Hungary (Magyarország)': CountryCodes.HU,
  'Iceland (Ísland)': CountryCodes.IS,
  'India (भारत)': CountryCodes.IN,
  Indonesia: CountryCodes.ID,
  Iran: CountryCodes.IR,
  Iraq: CountryCodes.IQ,
  Ireland: CountryCodes.IE,
  'Israel (‫ישראל‬‎)': CountryCodes.IL,
  'Italy (Italia)': CountryCodes.IT,
  Jamaica: CountryCodes.JM,
  'Jan Mayen': CountryCodes.SJ,
  'Japan (日本)': CountryCodes.JP,
  'Jarvis Island': CountryCodes.UM,
  Jersey: CountryCodes.JE,
  'Johnston Atoll': CountryCodes.UM,
  'Jordan (‫الأردن‬‎)': CountryCodes.JO,
  'Kazakhstan (Казахстан)': CountryCodes.KZ,
  Kenya: CountryCodes.KE,
  'Kingman Reef': CountryCodes.UM,
  Kiribati: CountryCodes.KI,
  "Korea, Democratic People's Republic of (North)": CountryCodes.KP,
  'Korea, Republic of (South) (대한민국)': CountryCodes.KR,
  Kosovo: CountryCodes.XK,
  'Kuwait (‫الكويت‬‎)': CountryCodes.KW,
  'Kyrgyzstan (Кыргызстан)': CountryCodes.KG,
  'Laos (ລາວ)': CountryCodes.LA,
  'Latvia (Latvija)': CountryCodes.LV,
  'Lebanon (‫لبنان‬‎)': CountryCodes.LB,
  Lesotho: CountryCodes.LS,
  Liberia: CountryCodes.LR,
  'Libya (‫ليبيا‬‎)': CountryCodes.LY,
  Liechtenstein: CountryCodes.LI,
  'Lithuania (Lietuva)': CountryCodes.LT,
  Luxembourg: CountryCodes.LU,
  'Macau (澳門)': CountryCodes.MO,
  'Macedonia (FYROM) (Македонија)': CountryCodes.MK,
  'Madagascar (Madagasikara)': CountryCodes.MG,
  Malawi: CountryCodes.MW,
  Malaysia: CountryCodes.MY,
  Maldives: CountryCodes.MV,
  Mali: CountryCodes.ML,
  Malta: CountryCodes.MT,
  'Man, Isle of': CountryCodes.IM,
  'Marshall Islands': CountryCodes.MH,
  'Mauritania (‫موريتانيا‬‎)': CountryCodes.MR,
  'Mauritius (Moris)': CountryCodes.MU,
  'Mexico (México)': CountryCodes.MX,
  'Midway Islands': CountryCodes.UM,
  'Moldova (Republica Moldova)': CountryCodes.MD,
  Monaco: CountryCodes.MC,
  'Mongolia (Монгол)': CountryCodes.MN,
  'Montenegro (Crna Gora)': CountryCodes.ME,
  Montserrat: CountryCodes.MS,
  'Morocco (‫المغرب‬‎)': CountryCodes.MA,
  'Mozambique (Moçambique)': CountryCodes.MZ,
  'Namibia (Namibië)': CountryCodes.NA,
  Nauru: CountryCodes.NR,
  'Navassa Island': CountryCodes.UM,
  'Nepal (नेपाल)': CountryCodes.NP,
  'Netherlands (Nederland)': CountryCodes.NL,
  'New Caledonia (Nouvelle-Calédonie)': CountryCodes.NC,
  'New Zealand': CountryCodes.NZ,
  Nicaragua: CountryCodes.NI,
  'Niger (Nijar)': CountryCodes.NE,
  Nigeria: CountryCodes.NG,
  Niue: CountryCodes.NU,
  'Norfolk Island': CountryCodes.NF,
  'Northern Mariana Islands': CountryCodes.MP,
  'Norway (Norge)': CountryCodes.NO,
  'Oman (‫عُمان‬‎)': CountryCodes.OM,
  'Pakistan (‫پاکستان‬‎)': CountryCodes.PK,
  Palau: CountryCodes.PW,
  'Palmyra Atoll': CountryCodes.UM,
  'Panama (Panamá)': CountryCodes.PA,
  'Papua-New Guinea': CountryCodes.PG,
  Paraguay: CountryCodes.PY,
  'Peru (Perú)': CountryCodes.PE,
  Philippines: CountryCodes.PH,
  'Pitcairn Islands': CountryCodes.PN,
  'Poland (Polska)': CountryCodes.PL,
  Portugal: CountryCodes.PT,
  'Puerto Rico': CountryCodes.PR,
  'Qatar (‫قطر‬‎)': CountryCodes.QA,
  'Romania (România)': CountryCodes.RO,
  'Russia (Россия)': CountryCodes.RU,
  Rwanda: CountryCodes.RW,
  'Saint Barthelemy': CountryCodes.BL,
  'Saint Martin (Saint-Martin (partie française))': CountryCodes.MF,
  Samoa: CountryCodes.WS,
  'San Marino': CountryCodes.SM,
  'Sao Tome and Principe (São Tomé e Príncipe)': CountryCodes.ST,
  'Saudi Arabia (‫المملكة العربية السعودية‬‎)': CountryCodes.SA,
  'Senegal (Sénégal)': CountryCodes.SN,
  'Serbia (Србија)': CountryCodes.RS,
  Seychelles: CountryCodes.SC,
  'Sierra Leone': CountryCodes.SL,
  Singapore: CountryCodes.SG,
  'Sint Maarten': CountryCodes.SX,
  'Slovakia (Slovensko)': CountryCodes.SK,
  'Slovenia (Slovenija)': CountryCodes.SI,
  'Solomon Islands': CountryCodes.SB,
  'Somalia (Soomaaliya)': CountryCodes.SO,
  'South Africa': CountryCodes.ZA,
  'South Georgia and the South Sandwich Islands': CountryCodes.GS,
  'South Sudan': CountryCodes.SS,
  'Spain (España)': CountryCodes.ES,
  'Sri Lanka (ශ්‍රී ලංකාව)': CountryCodes.LK,
  'St. Helena': CountryCodes.SH,
  'St. Kitts and Nevis': CountryCodes.KN,
  'St. Lucia Island': CountryCodes.LC,
  'St. Pierre and Miquelon (Saint-Pierre-et-Miquelon)': CountryCodes.PM,
  'St. Vincent and the Grenadines': CountryCodes.VC,
  Sudan: CountryCodes.SD,
  Suriname: CountryCodes.SR,
  Svalbard: CountryCodes.SJ,
  Swaziland: CountryCodes.SZ,
  'Sweden (Sverige)': CountryCodes.SE,
  'Switzerland (Schweiz)': CountryCodes.CH,
  Syria: CountryCodes.SY,
  'Taiwan (台灣)': CountryCodes.TW,
  Tajikistan: CountryCodes.TJ,
  Tanzania: CountryCodes.TZ,
  'Thailand (ไทย)': CountryCodes.TH,
  Togo: CountryCodes.TG,
  Tokelau: CountryCodes.TK,
  Tonga: CountryCodes.TO,
  'Trinidad and Tobago': CountryCodes.TT,
  'Tunisia (‫تونس‬‎)': CountryCodes.TN,
  'Turkey (Türkiye)': CountryCodes.TR,
  Turkmenistan: CountryCodes.TM,
  'Turks and Caicos Islands': CountryCodes.TC,
  Tuvalu: CountryCodes.TV,
  Uganda: CountryCodes.UG,
  'Ukraine (Україна)': CountryCodes.UA,
  'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)': CountryCodes.AE,
  'United Kingdom (England, Northern Ireland, Scotland, and Wales)': CountryCodes.GB,
  'United States of America': CountryCodes.US,
  Uruguay: CountryCodes.UY,
  'Uzbekistan (Oʻzbekiston)': CountryCodes.UZ,
  Vanuatu: CountryCodes.VU,
  Venezuela: CountryCodes.VE,
  'Vietnam (Việt Nam)': CountryCodes.VN,
  'Virgin Islands': CountryCodes.VI,
  'Wake Island': CountryCodes.UM,
  'Wallis and Futuna (Wallis-et-Futuna)': CountryCodes.WF,
  'Western Sahara (‫الصحراء الغربية‬‎)': CountryCodes.EH,
  'Yemen (Aden) (‫اليمن‬‎)': CountryCodes.YE,
  Zambia: CountryCodes.ZM,
  Zimbabwe: CountryCodes.ZW,
};
