export enum RiskAssessment {
  NotRecommended,
  Safe,
  PotentiallySafe,
}

export const MOCK_DATA = [
  {
    symbol: '1INCH',
    referencePrice: 0.438319018,
    numOracles: 4,
    liquidityTier: 2,
    riskAssessment: RiskAssessment.NotRecommended,
    p: -1,
    atomicResolution: -5,
    minExchanges: 3,
    minPriceChange: 4_000,
    priceExponent: -10,
    stepBaseQuanity: 1_000_000,
    tickSizeExponent: -3,
    subticksPerTick: 1_000_000,
    minOrderSize: 1_000_000,
    quantumConversionExponent: -9,
  },
  {
    symbol: 'AAVE',
    referencePrice: 104.5187949,
    numOracles: 6,
    liquidityTier: 2,
    riskAssessment: RiskAssessment.Safe,
    p: 2,
    atomicResolution: -8,
    minExchanges: 3,
    minPriceChange: 4_000,
    priceExponent: -7,
    stepBaseQuanity: 1_000_000,
    tickSizeExponent: -3,
    subticksPerTick: 1_000_000,
    minOrderSize: 1_000_000,
    quantumConversionExponent: -9,
  },
  {
    symbol: 'ACA',
    referencePrice: 0.1025584694,
    numOracles: 1,
    liquidityTier: 2,
    riskAssessment: RiskAssessment.NotRecommended,
    p: -1,
    atomicResolution: -5,
    minExchanges: 3,
    minPriceChange: 4_000,
    priceExponent: -10,
    stepBaseQuanity: 1_000_000,
    tickSizeExponent: -3,
    subticksPerTick: 1_000_000,
    minOrderSize: 1_000_000,
    quantumConversionExponent: -9,
  },
  {
    symbol: 'ALGO',
    referencePrice: 1.0,
    numOracles: 3,
    liquidityTier: 1,
    riskAssessment: RiskAssessment.PotentiallySafe,
    p: 0,
    atomicResolution: -6,
    minExchanges: 2,
    minPriceChange: 2_000,
    priceExponent: -8,
    stepBaseQuanity: 500_000,
    tickSizeExponent: -4,
    subticksPerTick: 500_000,
    minOrderSize: 500_000,
    quantumConversionExponent: -10,
  },
  {
    symbol: 'ATOM',
    referencePrice: 20.0,
    numOracles: 5,
    liquidityTier: 2,
    riskAssessment: RiskAssessment.Safe,
    p: 1,
    atomicResolution: -8,
    minExchanges: 3,
    minPriceChange: 5_000,
    priceExponent: -7,
    stepBaseQuanity: 1_000_000,
    tickSizeExponent: -3,
    subticksPerTick: 1_000_000,
    minOrderSize: 1_000_000,
    quantumConversionExponent: -9,
  },
];
