export const DEFAULT_PRIORITY_FEE_LAMPORTS = 100000;
export const DEFAULT_SLIPPAGE_BPS = 2000;

export const SPOT_DUST_USD_THRESHOLD = 0.01;
export const MIN_SOL_RESERVE = 0.002;
export const SOLANA_BASE_TRANSACTION_FEE = 0.000005;
export const SOL_WITHDRAWAL_POLL_INTERVAL_MS = 1000;
export const SOL_WITHDRAWAL_TIMEOUT_MS = 30000;
export const SPOT_DEFAULT_TOKEN_MINT = 'DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263';
