export const BOOSTED_MARKETS = new Set(['AIXBT-USD', 'KAITO-USD', 'SUI-USD', 'XRP-USD']);
export const BOOSTED_MARKETS_EXPIRATION = '2025-07-01T00:00:00.000Z';
export const CURRENT_REWARDS_SEASON = 3;
