* Ruscet Protocol

High-performance derivatives exchange built on the Fuel network. Smart Contracts written in Sway.

** Contract Addresses

|                |                           Address                                  |
|----------------+--------------------------------------------------------------------|
| Vault          | 0x8002f2e86302ef9421558d0ae25a68cdfdbec5d27915cc2db49eded220799ecc |
| VaultPricefeed | 0x3dfcb460ee3cd6dc2ac4be1fbe73c97ce9b4962aa429f4ebdbbfa8dd1d584b78 |
| RLPManager     | 0x5b210f226d57696d3d0fbf9c85e1232a045d50c12743d1b2cdbab17134eb80a9 |
| RLPContract    | 0x1d9d3b612524384c98e1cf03a1cda6a3aadb8ac794c9df87fe5ca6ac39ae3bcc |
| RLP (asset)    | 0x7da3cd371c72dddb5a2ffb133c070272555e6b8b3d23f3b8dc17900cc49c6cea |
| RUSDContract   | 0x80afa110507a0f1a05fd5c12ebb2f256f33b95cf9ff4d425beb7583234aa785c |
| RUSD (asset)   | 0x5d996c78c3b54f0c5eb96caa41b995ad7b9d6873acbfa5260883206f74bf912a |
| ShortsTracker  | 0xa94d01923b60c83430d722dc45ffbd634c57aa79edab554e5f18533f3e9436b6 |


** Overview

Trading on Ruscet is supported by multi-asset pools that earn liquidity provider fees from market-making, swap fees, and leveraged trading.

The main components of the protocol are:

1. Vault

Core contract handling all trading and liquidity operations. Acts as a peer-to-pool system where users trade against a pool of assets rather than directly with other users.

The contract manages:
- Pooled assets from liquidity providers
- Opening/closing of leveraged long/short positions
- Minting/burning of the RUSD stablecoin
- Liquidations and funding rates
- Swap functionality between supported assets

The Vault maintains solvency by ensuring the value of all assets in the pool exceeds the sum of all user deposits and profits. Position collateral is held in the Vault, and liquidations occur automatically when positions become undercollateralized.

2. RLP

Liquidity provider asset on the platform, and can be minted using any of the approved assets within the =Vault= pool such as =$ETH=, =$USDC=, and =$BTC=.

The price of RLP is pegged to the worth of all underlying assets within the =Vault=, factoring in profits and losses of all active positions.

3. Pricefeeds

=VaultPriceFeed= handles querying and updating of prices from the Pyth network for all assets within the =Vault= pool.


** Testing

#+begin_src shell
pnpm i;
pip install caer;
pnpm build; pnpm gen:types;

# --------- Testing ---------
fuel-core run --snapshot ./chain-config --debug --db-type in-memory --graphql-max-complexity 200000000;

pnpm test;
#+end_src

** Security

[[https://www.linumlabs.com][Linum Labs]] [[https://github.com/ruscetlabs/ruscet-contracts/tree/dev/audits][Ruscet v1 Audit Report]].

Immunefi [[https://immunefi.com/bug-bounty/ruscet/][bug bounty]].

** License

All code in this repository is protected under the Apache-2.0 License.
