import styled from 'styled-components';

import { Nullable } from '@/constants/abacus';

export type AssetSymbol = keyof typeof assetIcons;

const assetIcons = {
  '1CAT': '/currencies/1cat.png',
  '1INCH': '/currencies/1inch.png',
  A8: '/currencies/a8.png',
  AAVE: '/currencies/aave.png',
  ABBC: '/currencies/abbc.png',
  ACA: '/currencies/aca.png',
  ACE: '/currencies/ace.png',
  ACH: '/currencies/ach.png',
  ACM: '/currencies/acm.png',
  ACS: '/currencies/acs.png',
  ADA: '/currencies/ada.png',
  ADX: '/currencies/adx.png',
  AERGO: '/currencies/aergo.png',
  AERO: '/currencies/aero.png',
  AEVO: '/currencies/aevo.png',
  AFG: '/currencies/afg.png',
  AGI: '/currencies/agi.png',
  AGIX: '/currencies/agix.png',
  AGLD: '/currencies/agld.png',
  AIDOGE: '/currencies/aidoge.png',
  AIOZ: '/currencies/aioz.png',
  AITECH: '/currencies/aitech.png',
  AKRO: '/currencies/akro.png',
  AKT: '/currencies/akt.png',
  ALCX: '/currencies/alcx.png',
  ALEPH: '/currencies/aleph.png',
  ALGO: '/currencies/algo.png',
  ALICE: '/currencies/alice.png',
  ALPHA: '/currencies/alpha.png',
  ALPINE: '/currencies/alpine.png',
  ALT: '/currencies/alt.png',
  AMB: '/currencies/amb.png',
  AMP: '/currencies/amp.png',
  AMU: '/currencies/amu.png',
  ANALOS: '/currencies/analos.png',
  ANKR: '/currencies/ankr.png',
  ANT: '/currencies/ant.png',
  APE: '/currencies/ape.png',
  API3: '/currencies/api3.png',
  APP: '/currencies/app.png',
  APT: '/currencies/apt.png',
  AR: '/currencies/ar.png',
  ARB: '/currencies/arb.png',
  ARDR: '/currencies/ardr.png',
  ARG: '/currencies/arg.png',
  ARK: '/currencies/ark.png',
  ARKM: '/currencies/arkm.png',
  ARPA: '/currencies/arpa.png',
  ARTY: '/currencies/arty.png',
  AST: '/currencies/ast.png',
  ASTR: '/currencies/astr.png',
  ATA: '/currencies/ata.png',
  ATH: '/currencies/ath.png',
  ATM: '/currencies/atm.png',
  ATOM: '/currencies/atom.png',
  AUCTION: '/currencies/auction.png',
  AUDIO: '/currencies/audio.png',
  AURA: '/currencies/aura.png',
  AURORA: '/currencies/aurora.png',
  AURY: '/currencies/aury.png',
  AVA: '/currencies/ava.png',
  AVAIL: '/currencies/avail.png',
  AVAX: '/currencies/avax.png',
  AXL: '/currencies/axl.png',
  AXS: '/currencies/axs.png',
  AZERO: '/currencies/azero.png',
  AZY: '/currencies/azy.png',
  BADGER: '/currencies/badger.png',
  BAKE: '/currencies/bake.png',
  BAL: '/currencies/bal.png',
  BAND: '/currencies/band.png',
  BAR: '/currencies/bar.png',
  BAT: '/currencies/bat.png',
  BBL: '/currencies/bbl.png',
  BCH: '/currencies/bch.png',
  BCUT: '/currencies/bcut.png',
  BEAM: '/currencies/beam.png',
  BEER: '/currencies/beer.png',
  BEL: '/currencies/bel.png',
  BENDOG: '/currencies/bendog.png',
  BETH: '/currencies/beth.png',
  BFC: '/currencies/bfc.png',
  BICO: '/currencies/bico.png',
  BIGTIME: '/currencies/bigtime.png',
  BIT: '/currencies/bit.png',
  BLAST: '/currencies/blast.png',
  BLOCK: '/currencies/block.png',
  BLOK: '/currencies/blok.png',
  BLUR: '/currencies/blur.png',
  BLZ: '/currencies/blz.png',
  BNB: '/currencies/bnb.png',
  BNC: '/currencies/bnc.png',
  BNT: '/currencies/bnt.png',
  BNX: '/currencies/bnx.png',
  BOBA: '/currencies/boba.png',
  BODEN: '/currencies/boden.png',
  BOME: '/currencies/bome.png',
  BOND: '/currencies/bond.png',
  BONE: '/currencies/bone.png',
  BONK: '/currencies/bonk.png',
  BORING: '/currencies/boring.png',
  BORK: '/currencies/bork.png',
  BOSON: '/currencies/boson.png',
  BRAINLET: '/currencies/brainlet.png',
  BRAWL: '/currencies/brawl.png',
  BRETT: '/currencies/brett.png',
  BRL: '/currencies/brl.png',
  BRISE: '/currencies/brise.png',
  BRWL: '/currencies/brwl.png',
  BSV: '/currencies/bsv.png',
  BSW: '/currencies/bsw.png',
  BTC: '/currencies/btc.png',
  BTT: '/currencies/btt.png',
  BUBBLE: '/currencies/bubble.png',
  BUFFI: '/currencies/buffi.png',
  BURGER: '/currencies/burger.png',
  C98: '/currencies/c98.png',
  CAKE: '/currencies/cake.png',
  CANDY: '/currencies/candy.png',
  CAT: '/currencies/cat.png',
  CBK: '/currencies/cbk.png',
  CEEK: '/currencies/ceek.png',
  CEL: '/currencies/cel.png',
  CELO: '/currencies/celo.png',
  CELR: '/currencies/celr.png',
  CERE: '/currencies/cere.png',
  CETUS: '/currencies/cetus.png',
  CFG: '/currencies/cfg.png',
  CFX: '/currencies/cfx.png',
  CGPT: '/currencies/cgpt.png',
  CHAT: '/currencies/chat.png',
  CHR: '/currencies/chr.png',
  CHZ: '/currencies/chz.png',
  CITY: '/currencies/city.png',
  CKB: '/currencies/ckb.png',
  CLOUD: '/currencies/cloud.png',
  COMBO: '/currencies/combo.png',
  COMP: '/currencies/comp.png',
  COOKIE: '/currencies/cookie.png',
  COQ: '/currencies/coq.png',
  CORE: '/currencies/core.png',
  COST: '/currencies/cost.png',
  COTI: '/currencies/coti.png',
  CPOOL: '/currencies/cpool.png',
  CQT: '/currencies/cqt.png',
  CREAM: '/currencies/cream.png',
  CRO: '/currencies/cro.png',
  CRPT: '/currencies/crpt.png',
  CRV: '/currencies/crv.png',
  CSPR: '/currencies/cspr.png',
  CTA: '/currencies/cta.png',
  CTC: '/currencies/ctc.png',
  CTK: '/currencies/ctk.png',
  CTSI: '/currencies/ctsi.png',
  CTX: '/currencies/ctx.png',
  CTXC: '/currencies/ctxc.png',
  CUDOS: '/currencies/cudos.png',
  CULT: '/currencies/cult.png',
  CUSD: '/currencies/cusd.png',
  CVC: '/currencies/cvc.png',
  CVP: '/currencies/cvp.png',
  CVX: '/currencies/cvx.png',
  CWAR: '/currencies/cwar.png',
  CXT: '/currencies/cxt.png',
  CYBER: '/currencies/cyber.png',
  DADDY: '/currencies/daddy.png',
  DAG: '/currencies/dag.png',
  DAI: '/currencies/dai.png',
  DAO: '/currencies/dao.png',
  DAR: '/currencies/dar.png',
  DASH: '/currencies/dash.png',
  DATA: '/currencies/data.png',
  DC: '/currencies/dc.png',
  DCK: '/currencies/dck.png',
  DCR: '/currencies/dcr.png',
  DECHAT: '/currencies/dechat.png',
  DEFI: '/currencies/defi.png',
  DEGEN: '/currencies/degen.png',
  DEGO: '/currencies/dego.png',
  DENT: '/currencies/dent.png',
  DEP: '/currencies/dep.png',
  DESO: '/currencies/deso.png',
  DEXE: '/currencies/dexe.png',
  DF: '/currencies/df.png',
  DFI: '/currencies/dfi.png',
  DGB: '/currencies/dgb.png',
  DIA: '/currencies/dia.png',
  DKA: '/currencies/dka.png',
  DMAIL: '/currencies/dmail.png',
  DODO: '/currencies/dodo.png',
  DOGE: '/currencies/doge.png',
  DOGS: '/currencies/dogs.png',
  DOP: '/currencies/dop.png',
  DORA: '/currencies/dora.png',
  DOSE: '/currencies/dose.png',
  DOT: '/currencies/dot.png',
  DRIFT: '/currencies/drift.png',
  DUKO: '/currencies/duko.png',
  DUSK: '/currencies/dusk.png',
  DYDX: '/currencies/dydx.png',
  DYM: '/currencies/dym.png',
  DYP: '/currencies/dyp.png',
  ECOX: '/currencies/ecox.png',
  EDU: '/currencies/edu.png',
  EGLD: '/currencies/egld.png',
  EGO: '/currencies/ego.png',
  ELA: '/currencies/ela.png',
  ELF: '/currencies/elf.png',
  ELON: '/currencies/elon.png',
  ENA: '/currencies/ena.png',
  ENJ: '/currencies/enj.png',
  ENS: '/currencies/ens.png',
  EOS: '/currencies/eos.png',
  EPIK: '/currencies/epik.png',
  ERG: '/currencies/erg.png',
  ERN: '/currencies/ern.png',
  ERTHA: '/currencies/ertha.png',
  ESE: '/currencies/ese.png',
  ETC: '/currencies/etc.png',
  ETH: '/currencies/eth.png',
  ETHFI: '/currencies/ethfi.png',
  ETHW: '/currencies/ethw.png',
  EUL: '/currencies/eul.png',
  EUR: '/currencies/eur.png',
  EURC: '/currencies/eurc.png',
  EVER: '/currencies/ever.png',
  EWT: '/currencies/ewt.png',
  FALX: '/currencies/falx.png',
  FARM: '/currencies/farm.png',
  FET: '/currencies/fet.png',
  FIDA: '/currencies/fida.png',
  FIL: '/currencies/fil.png',
  FIO: '/currencies/fio.png',
  FIRE: '/currencies/fire.png',
  FIRO: '/currencies/firo.png',
  FIS: '/currencies/fis.png',
  FITFI: '/currencies/fitfi.png',
  FLIP: '/currencies/flip.png',
  FLM: '/currencies/flm.png',
  FLOKI: '/currencies/floki.png',
  FLOW: '/currencies/flow.png',
  FLR: '/currencies/flr.png',
  FLUX: '/currencies/flux.png',
  FOR: '/currencies/for.png',
  FORT: '/currencies/fort.png',
  FORTH: '/currencies/forth.png',
  FOXY: '/currencies/foxy.png',
  FRONT: '/currencies/front.png',
  FTM: '/currencies/ftm.png',
  FTT: '/currencies/ftt.png',
  FURY: '/currencies/fury.png',
  FX: '/currencies/fx.png',
  FXS: '/currencies/fxs.png',
  G: '/currencies/g.png',
  G3: '/currencies/g3.png',
  GAL: '/currencies/gal.png',
  GALA: '/currencies/gala.png',
  GARI: '/currencies/gari.png',
  GAS: '/currencies/gas.png',
  GFT: '/currencies/gft.png',
  GHST: '/currencies/ghst.png',
  GHX: '/currencies/ghx.png',
  GIGA: '/currencies/giga.png',
  GINNAN: '/currencies/ginnan.png',
  GLM: '/currencies/glm.png',
  GLMR: '/currencies/glmr.png',
  GME: '/currencies/gme.png',
  GMEE: '/currencies/gmee.png',
  GMRX: '/currencies/gmrx.png',
  GMT: '/currencies/gmt.png',
  GMX: '/currencies/gmx.png',
  GNO: '/currencies/gno.png',
  GNS: '/currencies/gns.png',
  GOAL: '/currencies/goal.png',
  GODS: '/currencies/gods.png',
  GOL: '/currencies/gol.png',
  GRAIL: '/currencies/grail.png',
  GRAPE: '/currencies/grape.png',
  GRT: '/currencies/grt.png',
  GST: '/currencies/gst.png',
  GTAI: '/currencies/gtai.png',
  GTC: '/currencies/gtc.png',
  GUAC: '/currencies/guac.png',
  GUMMY: '/currencies/gummy.png',
  GUSD: '/currencies/gusd.png',
  H2O: '/currencies/h2o.png',
  HAMMY: '/currencies/hammy.png',
  HARAMBE: '/currencies/harambe.png',
  HARD: '/currencies/hard.png',
  HBAR: '/currencies/hbar.png',
  HBB: '/currencies/hbb.png',
  HEGE: '/currencies/hege.png',
  HFT: '/currencies/hft.png',
  HIFI: '/currencies/hifi.png',
  HIGH: '/currencies/high.png',
  HIVE: '/currencies/hive.png',
  HLG: '/currencies/hlg.png',
  HNT: '/currencies/hnt.png',
  HOOK: '/currencies/hook.png',
  HOT: '/currencies/hot.png',
  HOTCROSS: '/currencies/hotcross.png',
  HTX: '/currencies/htx.png',
  ICE: '/currencies/ice.png',
  ICP: '/currencies/icp.png',
  ICX: '/currencies/icx.png',
  ID: '/currencies/id.png',
  IDEX: '/currencies/idex.png',
  IGU: '/currencies/igu.png',
  ILV: '/currencies/ilv.png',
  IMX: '/currencies/imx.png',
  INJ: '/currencies/inj.png',
  INSP: '/currencies/insp.png',
  IO: '/currencies/io.png',
  IOST: '/currencies/iost.png',
  IOTA: '/currencies/iota.png',
  IOTX: '/currencies/iotx.png',
  IQ: '/currencies/iq.png',
  IRL: '/currencies/irl.png',
  IZI: '/currencies/izi.png',
  JASMY: '/currencies/jasmy.png',
  JITOSOL: '/currencies/jitosol.png',
  JOE: '/currencies/joe.png',
  JST: '/currencies/jst.png',
  JTO: '/currencies/jto.png',
  JUP: '/currencies/jup.png',
  JUV: '/currencies/juv.png',
  KAN: '/currencies/kan.png',
  KARATE: '/currencies/karate.png',
  KARRAT: '/currencies/karrat.png',
  KAS: '/currencies/kas.png',
  KAVA: '/currencies/kava.png',
  KCAL: '/currencies/kcal.png',
  KCS: '/currencies/kcs.png',
  KDA: '/currencies/kda.png',
  KEY: '/currencies/key.png',
  KHAI: '/currencies/khai.png',
  KICKS: '/currencies/kicks.png',
  KLAY: '/currencies/klay.png',
  KLV: '/currencies/klv.png',
  KMD: '/currencies/kmd.png',
  KMNO: '/currencies/kmno.png',
  KNC: '/currencies/knc.png',
  KP3R: '/currencies/kp3r.png',
  KRL: '/currencies/krl.png',
  KSM: '/currencies/ksm.png',
  L3: '/currencies/l3.png',
  LADYS: '/currencies/ladys.png',
  LAI: '/currencies/lai.png',
  LAMB: '/currencies/lamb.png',
  LAT: '/currencies/lat.png',
  LBP: '/currencies/lbp.png',
  LBR: '/currencies/lbr.png',
  LCX: '/currencies/lcx.png',
  LDO: '/currencies/ldo.png',
  LENDS: '/currencies/lends.png',
  LEVER: '/currencies/lever.png',
  LFT: '/currencies/lft.png',
  LHINU: '/currencies/lhinu.png',
  LIKE: '/currencies/like.png',
  LINA: '/currencies/lina.png',
  LING: '/currencies/ling.png',
  LINK: '/currencies/link.png',
  LISTA: '/currencies/lista.png',
  LIT: '/currencies/lit.png',
  LITH: '/currencies/lith.png',
  LL: '/currencies/ll.png',
  LMWR: '/currencies/lmwr.png',
  LOKA: '/currencies/loka.png',
  LOOKS: '/currencies/looks.png',
  LOOM: '/currencies/loom.png',
  LPT: '/currencies/lpt.png',
  LQTY: '/currencies/lqty.png',
  LRC: '/currencies/lrc.png',
  LRDS: '/currencies/lrds.png',
  LSK: '/currencies/lsk.png',
  LTC: '/currencies/ltc.png',
  LTO: '/currencies/lto.png',
  LYX: '/currencies/lyx.png',
  MAGIC: '/currencies/magic.png',
  MANA: '/currencies/mana.png',
  MANEKI: '/currencies/maneki.png',
  MANTA: '/currencies/manta.png',
  MAPO: '/currencies/mapo.png',
  MASA: '/currencies/masa.png',
  MASK: '/currencies/mask.png',
  MATIC: '/currencies/matic.png',
  MAV: '/currencies/mav.png',
  MAVIA: '/currencies/mavia.png',
  MAX: '/currencies/max.png',
  MBL: '/currencies/mbl.png',
  MBOX: '/currencies/mbox.png',
  MBX: '/currencies/mbx.png',
  MCRT: '/currencies/mcrt.png',
  MDT: '/currencies/mdt.png',
  MELOS: '/currencies/melos.png',
  MEME: '/currencies/meme.png',
  MERL: '/currencies/merl.png',
  METIS: '/currencies/metis.png',
  MEW: '/currencies/mew.png',
  MICHI: '/currencies/michi.png',
  MINA: '/currencies/mina.png',
  MKR: '/currencies/mkr.png',
  MLK: '/currencies/mlk.png',
  MLN: '/currencies/mln.png',
  MNDE: '/currencies/mnde.png',
  MNT: '/currencies/mnt.png',
  MOBILE: '/currencies/mobile.png',
  MOG: '/currencies/mog.png',
  MON: '/currencies/mon.png',
  MOTHER: '/currencies/mother.png',
  MOVEZ: '/currencies/movez.png',
  MOVR: '/currencies/movr.png',
  MPL: '/currencies/mpl.png',
  MPLX: '/currencies/mplx.png',
  MSN: '/currencies/msn.png',
  MSOL: '/currencies/msol.png',
  MTL: '/currencies/mtl.png',
  MUBI: '/currencies/mubi.png',
  MUMU: '/currencies/mumu.png',
  MV: '/currencies/mv.png',
  MVL: '/currencies/mvl.png',
  MX: '/currencies/mx.png',
  MXC: '/currencies/mxc.png',
  MXM: '/currencies/mxm.png',
  MYRIA: '/currencies/myria.png',
  MYRO: '/currencies/myro.png',
  NAKA: '/currencies/naka.png',
  NAVX: '/currencies/navx.png',
  NEAR: '/currencies/near.png',
  NEIRO: '/currencies/neiro.png',
  NEO: '/currencies/neo.png',
  NEON: '/currencies/neon.png',
  NEXO: '/currencies/nexo.png',
  NFP: '/currencies/nfp.png',
  NFT: '/currencies/nft.png',
  NGL: '/currencies/ngl.png',
  NIBI: '/currencies/nibi.png',
  NKN: '/currencies/nkn.png',
  NLK: '/currencies/nlk.png',
  NMR: '/currencies/nmr.png',
  NODL: '/currencies/nodl.png',
  NOIA: '/currencies/noia.png',
  NOS: '/currencies/nos.png',
  NOT: '/currencies/not.png',
  NRN: '/currencies/nrn.png',
  NTRN: '/currencies/ntrn.png',
  NUB: '/currencies/nub.png',
  NULS: '/currencies/nuls.png',
  NUM: '/currencies/num.png',
  NYAN: '/currencies/nyan.png',
  NYM: '/currencies/nym.png',
  OAS: '/currencies/oas.png',
  OCEAN: '/currencies/ocean.png',
  OG: '/currencies/og.png',
  OGN: '/currencies/ogn.png',
  OGV: '/currencies/ogv.png',
  OKB: '/currencies/okb.png',
  OM: '/currencies/om.png',
  OMG: '/currencies/omg.png',
  OMN: '/currencies/omn.png',
  ONDO: '/currencies/ondo.png',
  ONE: '/currencies/one.png',
  ONG: '/currencies/ong.png',
  ONT: '/currencies/ont.png',
  OP: '/currencies/op.png',
  OPEN: '/currencies/open.png',
  OPUL: '/currencies/opul.png',
  ORAI: '/currencies/orai.png',
  ORB: '/currencies/orb.png',
  ORBS: '/currencies/orbs.png',
  ORCA: '/currencies/orca.png',
  ORDI: '/currencies/ordi.png',
  ORN: '/currencies/orn.png',
  OSMO: '/currencies/osmo.png',
  OXT: '/currencies/oxt.png',
  PAJAMAS: '/currencies/pajamas.png',
  PAXG: '/currencies/paxg.png',
  PBR: '/currencies/pbr.png',
  PBUX: '/currencies/pbux.png',
  PCI: '/currencies/pci.png',
  PDA: '/currencies/pda.png',
  PENDLE: '/currencies/pendle.png',
  PENG: '/currencies/peng.png',
  PEOPLE: '/currencies/people.png',
  PEPE: '/currencies/pepe.png',
  PERP: '/currencies/perp.png',
  PGN: '/currencies/pgn.png',
  PHA: '/currencies/pha.png',
  PHB: '/currencies/phb.png',
  PIP: '/currencies/pip.png',
  PIRATE: '/currencies/pirate.png',
  PIXEL: '/currencies/pixel.png',
  PIXFI: '/currencies/pixfi.png',
  PLU: '/currencies/plu.png',
  PNG: '/currencies/png.png',
  POKT: '/currencies/pokt.png',
  POL: '/currencies/pol.png',
  POLC: '/currencies/polc.png',
  POLS: '/currencies/pols.png',
  POLYX: '/currencies/polyx.png',
  POND: '/currencies/pond.png',
  PONKE: '/currencies/ponke.png',
  POPCAT: '/currencies/popcat.png',
  PORTAL: '/currencies/portal.png',
  POWR: '/currencies/powr.png',
  PRCL: '/currencies/prcl.png',
  PRIME: '/currencies/prime.png',
  PROM: '/currencies/prom.png',
  PRQ: '/currencies/prq.png',
  PSG: '/currencies/psg.png',
  PSTAKE: '/currencies/pstake.png',
  PUMLX: '/currencies/pumlx.png',
  PUNDIX: '/currencies/pundix.png',
  PUNDU: '/currencies/pundu.png',
  PUSH: '/currencies/push.png',
  PYR: '/currencies/pyr.png',
  PYTH: '/currencies/pyth.png',
  PYUSD: '/currencies/pyusd.png',
  QI: '/currencies/qi.png',
  QKC: '/currencies/qkc.png',
  QNT: '/currencies/qnt.png',
  QORPO: '/currencies/qorpo.png',
  QTUM: '/currencies/qtum.png',
  RACA: '/currencies/raca.png',
  RAD: '/currencies/rad.png',
  RANKER: '/currencies/ranker.png',
  RARE: '/currencies/rare.png',
  RARI: '/currencies/rari.png',
  RAY: '/currencies/ray.png',
  RBN: '/currencies/rbn.png',
  RDNT: '/currencies/rdnt.png',
  REEF: '/currencies/reef.png',
  REI: '/currencies/rei.png',
  REN: '/currencies/ren.png',
  RENDER: '/currencies/render.png',
  REQ: '/currencies/req.png',
  RETARDIO: '/currencies/retardio.png',
  REVV: '/currencies/revv.png',
  REZ: '/currencies/rez.png',
  RIF: '/currencies/rif.png',
  RIO: '/currencies/rio.png',
  RLC: '/currencies/rlc.png',
  RNDR: '/currencies/rndr.png',
  RNT: '/currencies/rnt.png',
  ROOT: '/currencies/root.png',
  ROSE: '/currencies/rose.png',
  ROUTE: '/currencies/route.png',
  RPL: '/currencies/rpl.png',
  RSR: '/currencies/rsr.png',
  RSS3: '/currencies/rss3.png',
  RUNE: '/currencies/rune.png',
  RVN: '/currencies/rvn.png',
  SAFE: '/currencies/safe.png',
  SAGA: '/currencies/saga.png',
  SAMO: '/currencies/samo.png',
  SAND: '/currencies/sand.png',
  SAROS: '/currencies/saros.png',
  SATS: '/currencies/sats.png',
  SC: '/currencies/sc.png',
  SCA: '/currencies/sca.png',
  SCRT: '/currencies/scrt.png',
  SD: '/currencies/sd.png',
  SDAO: '/currencies/sdao.png',
  SEAM: '/currencies/seam.png',
  SEI: '/currencies/sei.png',
  SELFIE: '/currencies/selfie.png',
  SFP: '/currencies/sfp.png',
  SFUND: '/currencies/sfund.png',
  SGB: '/currencies/sgb.png',
  SHIB: '/currencies/shib.png',
  SHRAP: '/currencies/shrap.png',
  SIDUS: '/currencies/sidus.png',
  SILLY: '/currencies/silly.png',
  SIS: '/currencies/sis.png',
  SKL: '/currencies/skl.png',
  SLERF: '/currencies/slerf.png',
  SLOTH: '/currencies/sloth.png',
  SLP: '/currencies/slp.png',
  SMOLE: '/currencies/smole.png',
  SNT: '/currencies/snt.png',
  SNX: '/currencies/snx.png',
  SOL: '/currencies/sol.png',
  SOLAMA: '/currencies/solama.png',
  SOLO: '/currencies/solo.png',
  SON: '/currencies/son.png',
  SPA: '/currencies/spa.png',
  SPELL: '/currencies/spell.png',
  SQD: '/currencies/sqd.png',
  SQR: '/currencies/sqr.png',
  SRM: '/currencies/srm.png',
  SSV: '/currencies/ssv.png',
  STC: '/currencies/stc.png',
  STEEM: '/currencies/steem.png',
  STG: '/currencies/stg.png',
  STORJ: '/currencies/storj.png',
  STPT: '/currencies/stpt.png',
  STRAX: '/currencies/strax.png',
  STRK: '/currencies/strk.png',
  STRM: '/currencies/strm.png',
  STX: '/currencies/stx.png',
  SUI: '/currencies/sui.png',
  SUIA: '/currencies/suia.png',
  SUKU: '/currencies/suku.png',
  SUN: '/currencies/sun.png',
  SUNDOG: '/currencies/sundog.png',
  SUPER: '/currencies/super.png',
  SUSHI: '/currencies/sushi.png',
  SWEAT: '/currencies/sweat.png',
  SWFTC: '/currencies/swftc.png',
  SXP: '/currencies/sxp.png',
  SYLO: '/currencies/sylo.png',
  SYN: '/currencies/syn.png',
  SYNT: '/currencies/synt.png',
  SYS: '/currencies/sys.png',
  T: '/currencies/t.png',
  TAIKO: '/currencies/taiko.png',
  TAMA: '/currencies/tama.png',
  TAO: '/currencies/tao.png',
  TAVA: '/currencies/tava.png',
  TEL: '/currencies/tel.png',
  TENET: '/currencies/tenet.png',
  TFUEL: '/currencies/tfuel.png',
  THETA: '/currencies/theta.png',
  TIA: '/currencies/tia.png',
  TIME: '/currencies/time.png',
  TLM: '/currencies/tlm.png',
  TLOS: '/currencies/tlos.png',
  TNSR: '/currencies/tnsr.png',
  TOMI: '/currencies/tomi.png',
  TON: '/currencies/ton.png',
  TOOKER: '/currencies/tooker.png',
  TRAC: '/currencies/trac.png',
  TRB: '/currencies/trb.png',
  TREMP: '/currencies/tremp.png',
  TRIBE: '/currencies/tribe.png',
  TRU: '/currencies/tru.png',
  TRUMP: '/currencies/trump.png',
  TRUMPWIN: '/currencies/trumpwin.png',
  TRVL: '/currencies/trvl.png',
  TRX: '/currencies/trx.png',
  TRY: '/currencies/try.png',
  TST: '/currencies/tst.png',
  TT: '/currencies/tt.png',
  TURBO: '/currencies/turbo.png',
  TURBOS: '/currencies/turbos.png',
  TUSD: '/currencies/tusd.png',
  TWT: '/currencies/twt.png',
  UFT: '/currencies/uft.png',
  ULTI: '/currencies/ulti.png',
  UMA: '/currencies/uma.png',
  UNB: '/currencies/unb.png',
  UNFI: '/currencies/unfi.png',
  UNI: '/currencies/uni.png',
  UOS: '/currencies/uos.png',
  USDC: '/currencies/usdc.png',
  USDD: '/currencies/usdd.png',
  USDE: '/currencies/usde.png',
  USDJ: '/currencies/usdj.png',
  USDP: '/currencies/usdp.png',
  USDT: '/currencies/usdt.png',
  USTC: '/currencies/ustc.png',
  UTK: '/currencies/utk.png',
  UXLINK: '/currencies/uxlink.png',
  VANRY: '/currencies/vanry.png',
  VEGA: '/currencies/vega.png',
  VELA: '/currencies/vela.png',
  VELO: '/currencies/velo.png',
  VEMP: '/currencies/vemp.png',
  VENOM: '/currencies/venom.png',
  VET: '/currencies/vet.png',
  VEXT: '/currencies/vext.png',
  VIC: '/currencies/vic.png',
  VIDT: '/currencies/vidt.png',
  VINU: '/currencies/vinu.png',
  VLX: '/currencies/vlx.png',
  VOLT: '/currencies/volt.png',
  VOXEL: '/currencies/voxel.png',
  VPAD: '/currencies/vpad.png',
  VR: '/currencies/vr.png',
  VRA: '/currencies/vra.png',
  VRTX: '/currencies/vrtx.png',
  VSYS: '/currencies/vsys.png',
  VTHO: '/currencies/vtho.png',
  W: '/currencies/w.png',
  WAFFLES: '/currencies/waffles.png',
  WAN: '/currencies/wan.png',
  WAVES: '/currencies/waves.png',
  WAXP: '/currencies/waxp.png',
  WBTC: '/currencies/wbtc.png',
  WELL: '/currencies/well.png',
  WEMIX: '/currencies/wemix.png',
  WEN: '/currencies/wen.png',
  WETH: '/currencies/weth.png',
  WHALE: '/currencies/whale.png',
  WIF: '/currencies/wif.png',
  WIFI: '/currencies/wifi.png',
  WILD: '/currencies/wild.png',
  WIN: '/currencies/win.png',
  WLD: '/currencies/wld.png',
  WLKN: '/currencies/wlkn.png',
  WMT: '/currencies/wmt.png',
  WOLF: '/currencies/wolf.png',
  WOO: '/currencies/woo.png',
  WRX: '/currencies/wrx.png',
  WSDM: '/currencies/wsdm.png',
  WSM: '/currencies/wsm.png',
  WSTETH: '/currencies/wsteth.png',
  WUF: '/currencies/wuf.png',
  WWY: '/currencies/wwy.png',
  WXT: '/currencies/wxt.png',
  WYNN: '/currencies/wynn.png',
  XAI: '/currencies/xai.png',
  XAVA: '/currencies/xava.png',
  XCAD: '/currencies/xcad.png',
  XCH: '/currencies/xch.png',
  XCN: '/currencies/xcn.png',
  XCUR: '/currencies/xcur.png',
  XDC: '/currencies/xdc.png',
  XDEFI: '/currencies/xdefi.png',
  XEC: '/currencies/xec.png',
  XEM: '/currencies/xem.png',
  XETA: '/currencies/xeta.png',
  XLM: '/currencies/xlm.png',
  XMR: '/currencies/xmr.png',
  XNO: '/currencies/xno.png',
  XPLA: '/currencies/xpla.png',
  XPR: '/currencies/xpr.png',
  XPRT: '/currencies/xprt.png',
  XR: '/currencies/xr.png',
  XRD: '/currencies/xrd.png',
  XRP: '/currencies/xrp.png',
  XTM: '/currencies/xtm.png',
  XTZ: '/currencies/xtz.png',
  XVG: '/currencies/xvg.png',
  XWG: '/currencies/xwg.png',
  XYM: '/currencies/xym.png',
  XYO: '/currencies/xyo.png',
  XZK: '/currencies/xzk.png',
  YFI: '/currencies/yfi.png',
  YGG: '/currencies/ygg.png',
  ZACK: '/currencies/zack.png',
  ZBCN: '/currencies/zbcn.png',
  ZCX: '/currencies/zcx.png',
  ZEC: '/currencies/zec.png',
  ZELIX: '/currencies/zelix.png',
  ZEN: '/currencies/zen.png',
  ZEND: '/currencies/zend.png',
  ZENT: '/currencies/zent.png',
  ZERO: '/currencies/zero.png',
  ZETA: '/currencies/zeta.png',
  ZEUS: '/currencies/zeus.png',
  ZEX: '/currencies/zex.png',
  ZIG: '/currencies/zig.png',
  ZIL: '/currencies/zil.png',
  ZK: '/currencies/zk.png',
  ZKF: '/currencies/zkf.png',
  ZKJ: '/currencies/zkj.png',
  ZKL: '/currencies/zkl.png',
  ZRO: '/currencies/zro.png',
  ZRX: '/currencies/zrx.png',
  '00': '/currencies/00.png',
  '0DOG': '/currencies/0dog.png',
  '1000SATS': '/currencies/1000sats.png',
  '10SET': '/currencies/10set.png',
  '1CAT,UNISWAP_V3,0X508E00D5CEF397B02D260D035E5EE80775E4C821':
    '/currencies/1cat,uniswap_v3,0x508e00d5cef397b02d260d035e5ee80775e4c821.png',
  '1SOL': '/currencies/1sol.png',
  '5IRE': '/currencies/5ire.png',
  AARK: '/currencies/aark.png',
  'AART,RAYDIUM,F3NEFJBCEJYBTDREJUI1T9DPH5DBGPKKQ7U2GAAMXS5B':
    '/currencies/aart,raydium,f3nefjbcejybtdrejui1t9dph5dbgpkkq7u2gaamxs5b.png',
  ABT: '/currencies/abt.png',
  ACX: '/currencies/acx.png',
  ADS: '/currencies/ads.png',
  AEUR: '/currencies/aeur.png',
  AGG: '/currencies/agg.png',
  AGLA: '/currencies/agla.png',
  'AGRS,UNISWAP_V3,0X738865301A9B7DD80DC3666DD48CF034EC42BDDA':
    '/currencies/agrs,uniswap_v3,0x738865301a9b7dd80dc3666dd48cf034ec42bdda.png',
  AI: '/currencies/ai.png',
  AIPAD: '/currencies/aipad.png',
  AIT: '/currencies/ait.png',
  AKI: '/currencies/aki.png',
  AKITA: '/currencies/akita.png',
  AL: '/currencies/al.png',
  ALEO: '/currencies/aleo.png',
  'ALEPH,UNISWAP_V3,0X27702A26126E0B3702AF63EE09AC4D1A084EF628':
    '/currencies/aleph,uniswap_v3,0x27702a26126e0b3702af63ee09ac4d1a084ef628.png',
  ALEX: '/currencies/alex.png',
  ALI: '/currencies/ali.png',
  ALPACA: '/currencies/alpaca.png',
  ALPH: '/currencies/alph.png',
  ALU: '/currencies/alu.png',
  AMPL: '/currencies/ampl.png',
  'ANALOS,RAYDIUM,7IT1GRYYHEOP2NV1DYCWK2MGYLMPHQ47WHPGSWIQCUG5':
    '/currencies/analos,raydium,7it1gryyheop2nv1dycwk2mgylmphq47whpgswiqcug5.png',
  'ANDY,UNISWAP_V3,0X68BBED6A47194EFF1CF514B50EA91895597FC91E':
    '/currencies/andy,uniswap_v3,0x68bbed6a47194eff1cf514b50ea91895597fc91e.png',
  'ANUS,RAYDIUM,9HJZ8UTNRNWT3YUTHVPVZDQJNBP64NBKSDSBLQKR6BZC':
    '/currencies/anus,raydium,9hjz8utnrnwt3yuthvpvzdqjnbp64nbksdsblqkr6bzc.png',
  ANYONE: '/currencies/anyone.png',
  'APES,RAYDIUM,984GBL7PHCECHTN64NWLDBB49RSQXX7OZPDKEBR1PUMP':
    '/currencies/apes,raydium,984gbl7phcechtn64nwldbb49rsqxx7ozpdkebr1pump.png',
  APEX: '/currencies/apex.png',
  APRS: '/currencies/aprs.png',
  APTR: '/currencies/aptr.png',
  APU: '/currencies/apu.png',
  ARS: '/currencies/ars.png',
  ARTFI: '/currencies/artfi.png',
  ASM: '/currencies/asm.png',
  ASR: '/currencies/asr.png',
  ASTO: '/currencies/asto.png',
  ATLAS: '/currencies/atlas.png',
  'ATLAS,RAYDIUM,ATLASXMBPQXBUYBXPSV97USA3FPQYEQZQBUHGIFCUSXX':
    '/currencies/atlas,raydium,atlasxmbpqxbuybxpsv97usa3fpqyeqzqbuhgifcusxx.png',
  'AURA,RAYDIUM,DTR4D9FTVOTX2569GAL837ZGRB6WNJJ6TKMNX9RDK9B2':
    '/currencies/aura,raydium,dtr4d9ftvotx2569gal837zgrb6wnjj6tkmnx9rdk9b2.png',
  'AVI,UNISWAP_V3,0XD2BDAAF2B9CC6981FD273DCB7C04023BFBE0A7FE':
    '/currencies/avi,uniswap_v3,0xd2bdaaf2b9cc6981fd273dcb7c04023bfbe0a7fe.png',
  AVIVE: '/currencies/avive.png',
  AVT: '/currencies/avt.png',
  AZUR: '/currencies/azur.png',
  'BABY,RAYDIUM,5HMF8JT9PUWOQIFQTB3VR22732ZTKYRLRW9VO7TN3RCZ':
    '/currencies/baby,raydium,5hmf8jt9puwoqifqtb3vr22732ztkyrlrw9vo7tn3rcz.png',
  BABYDOGE: '/currencies/babydoge.png',
  'BABYTRUMP,RAYDIUM,6NBNHQKD2DH4JSWTLMMCP7LNSH4NH6Y2CNGDQG2NY9ZW':
    '/currencies/babytrump,raydium,6nbnhqkd2dh4jswtlmmcp7lnsh4nh6y2cngdqg2ny9zw.png',
  'BAG,RAYDIUM,D8R8XTUCRUHLHEWEGXSWC3G92RHASFICV3YA7B2XWCLV':
    '/currencies/bag,raydium,d8r8xtucruhlhewegxswc3g92rhasficv3ya7b2xwclv.png',
  'BAKED,RAYDIUM,CQBXK942C6GPCRWTZ2WMFP5JCQ9NQBXTB8JUEWBI7GOT':
    '/currencies/baked,raydium,cqbxk942c6gpcrwtz2wmfp5jcq9nqbxtb8juewbi7got.png',
  BANANA: '/currencies/banana.png',
  BB: '/currencies/bb.png',
  BCCOIN: '/currencies/bccoin.png',
  'BDROP,RAYDIUM,DCJLACAUR25RUJGXBVHZTCWPCTJZSW6YDM8E7OIPIT3K':
    '/currencies/bdrop,raydium,dcjlacaur25rujgxbvhztcwpctjzsw6ydm8e7oipit3k.png',
  BDX: '/currencies/bdx.png',
  BEAT: '/currencies/beat.png',
  BEBE: '/currencies/bebe.png',
  'BENDOG,RAYDIUM,AHW5N8IQZOBTCBEPKSJZZ61XTAUSZBDCPXTRLG6KUKPK':
    '/currencies/bendog,raydium,ahw5n8iqzobtcbepksjzz61xtauszbdcpxtrlg6kukpk.png',
  BENJI: '/currencies/benji.png',
  BEPRO: '/currencies/bepro.png',
  BETA: '/currencies/beta.png',
  'BGUY,UNISWAP-V3-BASE,0X8931EE05EC111325C1700B68E5EF7B887E00661D':
    '/currencies/bguy,uniswap-v3-base,0x8931ee05ec111325c1700b68e5ef7b887e00661d.png',
  BIFI: '/currencies/bifi.png',
  'BILL,RAYDIUM,5O817YNOR97F1H5SUZBGHWC8DP53OURERUFBGJIACFUZ':
    '/currencies/bill,raydium,5o817ynor97f1h5suzbghwc8dp53ourerufbgjiacfuz.png',
  BILLY: '/currencies/billy.png',
  'BITCOIN,UNISWAP_V3,0X72E4F9F808C49A2A61DE9C5896298920DC4EEEA9':
    '/currencies/bitcoin,uniswap_v3,0x72e4f9f808c49a2a61de9c5896298920dc4eeea9.png',
  'BKN,UNISWAP_V3,0X0A638F07ACC6969ABF392BB009F216D22ADEA36D':
    '/currencies/bkn,uniswap_v3,0x0a638f07acc6969abf392bb009f216d22adea36d.png',
  BLAZE: '/currencies/blaze.png',
  BLD: '/currencies/bld.png',
  BLS: '/currencies/bls.png',
  'BLUE,RAYDIUM,CWQVQTKUH1IU8ZSFFFVAUXAVZLZQU1E8GYU5D6ECGBNE':
    '/currencies/blue,raydium,cwqvqtkuh1iu8zsfffvauxavzlzqu1e8gyu5d6ecgbne.png',
  BMX: '/currencies/bmx.png',
  BOB: '/currencies/bob.png',
  'BOBAOPPA,RAYDIUM,BOBAM3U8QMQZHY1HWATNVZE9DLXVKGKYK3TD3T8MLVA':
    '/currencies/bobaoppa,raydium,bobam3u8qmqzhy1hwatnvze9dlxvkgkyk3td3t8mlva.png',
  BOBO: '/currencies/bobo.png',
  'BODEN,RAYDIUM,3PSH1MJ1F7YUFAD5GH6ZJ7EPE8HHRMKMETGV5TSHQA4O':
    '/currencies/boden,raydium,3psh1mj1f7yufad5gh6zj7epe8hhrmkmetgv5tshqa4o.png',
  BONUS: '/currencies/bonus.png',
  'BOOE,UNISWAP_V3,0X289FF00235D2B98B0145FF5D4435D3E92F9540A6':
    '/currencies/booe,uniswap_v3,0x289ff00235d2b98b0145ff5d4435d3e92f9540a6.png',
  BORA: '/currencies/bora.png',
  'BORK,RAYDIUM,4JZXKSNGTQKCDB36ECZ6A2ANZCUNIGCDEXGTDTM2HXAX':
    '/currencies/bork,raydium,4jzxksngtqkcdb36ecz6a2anzcunigcdexgtdtm2hxax.png',
  'BOZO,RAYDIUM,EJPTJEDOGXZDBVM8QVASQYBLMPJ5N1VQEQOAZJ9YFV3Q':
    '/currencies/bozo,raydium,ejptjedogxzdbvm8qvasqyblmpj5n1vqeqoazj9yfv3q.png',
  'BRAINLET,RAYDIUM,8NNXWRWVCTNW1UFEABYPFFIMTDCLCCD8XJZHVYSMGWPF':
    '/currencies/brainlet,raydium,8nnxwrwvctnw1ufeabypffimtdclccd8xjzhvysmgwpf.png',
  BRZ: '/currencies/brz.png',
  BST: '/currencies/bst.png',
  BTRST: '/currencies/btrst.png',
  'BTW,RAYDIUM,4YTPZGVONB66BFS6NRCUAAVSLDTYK2FHQ4U92JNJPUMP':
    '/currencies/btw,raydium,4ytpzgvonb66bfs6nrcuaavsldtyk2fhq4u92jnjpump.png',
  'BUFFI,UNISWAP_V3,0X4C1B1302220D7DE5C22B495E78B72F2DD2457D45':
    '/currencies/buffi,uniswap_v3,0x4c1b1302220d7de5c22b495e78b72f2dd2457d45.png',
  'BWB,RAYDIUM,6FVYLVHQSSHWVUSCQ2FJRR1MRECGSHC3QXBWWTGIVFWK':
    '/currencies/bwb,raydium,6fvylvhqsshwvuscq2fjrr1mrecgshc3qxbwwtgivfwk.png',
  'BYTE,RAYDIUM,ARGFK9JJ72QETCMCKXVJCZ9APUATGP1MF9YSVHNPU4UT':
    '/currencies/byte,raydium,argfk9jj72qetcmckxvjcz9apuatgp1mf9ysvhnpu4ut.png',
  'BYTES,UNISWAP_V3,0XA19F5264F7D7BE11C451C093D8F92592820BEA86':
    '/currencies/bytes,uniswap_v3,0xa19f5264f7d7be11c451c093d8f92592820bea86.png',
  BZZ: '/currencies/bzz.png',
  CA: '/currencies/ca.png',
  CAGA: '/currencies/caga.png',
  'CAH,UNISWAP_V3,0X8E0E57DCB1CE8D9091DF38EC1BFC3B224529754A':
    '/currencies/cah,uniswap_v3,0x8e0e57dcb1ce8d9091df38ec1bfc3b224529754a.png',
  'CAIR,RAYDIUM,D7Z8T6FADMQDYGHY3LSMN3BZFRABMVVUNAFURKFUWZ8F':
    '/currencies/cair,raydium,d7z8t6fadmqdyghy3lsmn3bzfrabmvvunafurkfuwz8f.png',
  'CAL,UNISWAP_V3,0X20561172F791F915323241E885B4F7D5187C36E1':
    '/currencies/cal,uniswap_v3,0x20561172f791f915323241e885b4f7d5187c36e1.png',
  CAPS: '/currencies/caps.png',
  'CATALORIAN,UNISWAP_V3,0X8BAF5D75CAE25C7DF6D1E0D26C52D19EE848301A':
    '/currencies/catalorian,uniswap_v3,0x8baf5d75cae25c7df6d1e0d26c52d19ee848301a.png',
  CATDOG: '/currencies/catdog.png',
  'CATGPT,RAYDIUM,FGF1US3KQU9AXU2X1YWKFIKE8USX42ACVRIURBUAODZQ':
    '/currencies/catgpt,raydium,fgf1us3kqu9axu2x1ywkfike8usx42acvriurbuaodzq.png',
  CATI: '/currencies/cati.png',
  'CATMAN,RAYDIUM,EAVJDLH8CYTANT3QDITPKGMSPL2HQ1MY5G9R2P6AT6LC':
    '/currencies/catman,raydium,eavjdlh8cytant3qditpkgmspl2hq1my5g9r2p6at6lc.png',
  CAW: '/currencies/caw.png',
  'CBETH,UNISWAP_V3,0XBE9895146F7AF43049CA1C1AE358B0541EA49704':
    '/currencies/cbeth,uniswap_v3,0xbe9895146f7af43049ca1c1ae358b0541ea49704.png',
  CBX: '/currencies/cbx.png',
  CCD: '/currencies/ccd.png',
  CDCETH: '/currencies/cdceth.png',
  'CDT,RAYDIUM,AK3OVNWQNAXPSFOSNCONYJLNJTQDCKRBH4HWHWKB6HFM':
    '/currencies/cdt,raydium,ak3ovnwqnaxpsfosnconyjlnjtqdckrbh4hwhwkb6hfm.png',
  CEC: '/currencies/cec.png',
  CHAPZ: '/currencies/chapz.png',
  'CHAT,RAYDIUM,947TEOG318GUMYJVYHRANRVWPMX7FPBTDQFBOJVSKSG3':
    '/currencies/chat,raydium,947teog318gumyjvyhranrvwpmx7fpbtdqfbojvsksg3.png',
  'CHEEKS,RAYDIUM,6E6RVIDZAVLRV56NVZYE5UOFRKDG36MF6DTQRMCOPTW9':
    '/currencies/cheeks,raydium,6e6rvidzavlrv56nvzye5uofrkdg36mf6dtqrmcoptw9.png',
  CHEEL: '/currencies/cheel.png',
  'CHEEMS,RAYDIUM,3FOUASGDBVTD6YZ4WVKJGTB76ONJUKZ7GPEBNIR5B8WC':
    '/currencies/cheems,raydium,3fouasgdbvtd6yz4wvkjgtb76onjukz7gpebnir5b8wc.png',
  'CHEEMS,UNISWAP_V3,0X41B1F9DCD5923C9542B6957B9B72169595ACBC5C':
    '/currencies/cheems,uniswap_v3,0x41b1f9dcd5923c9542b6957b9b72169595acbc5c.png',
  CHEQ: '/currencies/cheq.png',
  CHESS: '/currencies/chess.png',
  'CHEX,RAYDIUM,6DKCOWJPJ5MFU5GWDEFDPUUEBASBLK3WLEWHUZQPAA1E':
    '/currencies/chex,raydium,6dkcowjpj5mfu5gwdefdpuuebasblk3wlewhuzqpaa1e.png',
  CHF: '/currencies/chf.png',
  'CHILL,RAYDIUM,BZPQOPC44OAHU9SB5HEK1GRNJZC4UWFCL4OWUSWOZM3N':
    '/currencies/chill,raydium,bzpqopc44oahu9sb5hek1grnjzc4uwfcl4owuswozm3n.png',
  'CHINU,RAYDIUM,FLRGWXXAX8Q8ECF18WEDF3PLAYORXST5ORPY34D8JFBM':
    '/currencies/chinu,raydium,flrgwxxax8q8ecf18wedf3playorxst5orpy34d8jfbm.png',
  'CHITAN,RAYDIUM,J95PXHUEYTZTGBF9DPLPYPHXNUTWN4FBRK2JNC5NYKA3':
    '/currencies/chitan,raydium,j95pxhueytztgbf9dplpyphxnutwn4fbrk2jnc5nyka3.png',
  'CHONKY,RAYDIUM,H7ED7UGCLP3AX4X1CQ5WUWDN6D1PPRFMMYIV5EJWLWWU':
    '/currencies/chonky,raydium,h7ed7ugclp3ax4x1cq5wuwdn6d1pprfmmyiv5ejwlwwu.png',
  CHRP: '/currencies/chrp.png',
  CLV: '/currencies/clv.png',
  CO: '/currencies/co.png',
  'COK,RAYDIUM,DNB9DLSXXAARXVEXEHZEH8W8NFMLMNJSUGOADDZSWTOG':
    '/currencies/cok,raydium,dnb9dlsxxaarxvexehzeh8w8nfmlmnjsugoaddzswtog.png',
  COM: '/currencies/com.png',
  CONV: '/currencies/conv.png',
  COP: '/currencies/cop.png',
  COREUM: '/currencies/coreum.png',
  COS: '/currencies/cos.png',
  'COST,RAYDIUM,AV6QVIGKB7USQYPXJKUVAEM4F599WTRVD75PUWBA9ENM':
    '/currencies/cost,raydium,av6qvigkb7usqypxjkuvaem4f599wtrvd75puwba9enm.png',
  COT: '/currencies/cot.png',
  CRDS: '/currencies/crds.png',
  'CREAM,UNISWAP_V3,0X2BA592F78DB6436527729929AAF6C908497CB200':
    '/currencies/cream,uniswap_v3,0x2ba592f78db6436527729929aaf6c908497cb200.png',
  CREDI: '/currencies/credi.png',
  CREO: '/currencies/creo.png',
  CRTS: '/currencies/crts.png',
  CSIX: '/currencies/csix.png',
  CTP: '/currencies/ctp.png',
  CTT: '/currencies/ctt.png',
  CVTX: '/currencies/cvtx.png',
  CWEB: '/currencies/cweb.png',
  CZK: '/currencies/czk.png',
  DAPP: '/currencies/dapp.png',
  DAPPX: '/currencies/dappx.png',
  'DATA,UNISWAP_V3,0X8F693CA8D21B157107184D29D398A8D082B38B76':
    '/currencies/data,uniswap_v3,0x8f693ca8d21b157107184d29d398a8d082b38b76.png',
  DCB: '/currencies/dcb.png',
  DEVVE: '/currencies/devve.png',
  'DEVVE,UNISWAP_V3,0X8248270620AA532E4D64316017BE5E873E37CC09':
    '/currencies/devve,uniswap_v3,0x8248270620aa532e4d64316017be5e873e37cc09.png',
  DFYN: '/currencies/dfyn.png',
  DIMO: '/currencies/dimo.png',
  'DINGO,RAYDIUM,6VYF5JXQ6RFQ4QRGGMG6CO7B1EV1LJ7KSBHBXFQ9E1L3':
    '/currencies/dingo,raydium,6vyf5jxq6rfq4qrggmg6co7b1ev1lj7ksbhbxfq9e1l3.png',
  DIONE: '/currencies/dione.png',
  DLC: '/currencies/dlc.png',
  'DLORD,RAYDIUM,3KRWSXRWEUBPSDJ9NKIWZNJSXLQKDPJNGZEEU5MZKKRB':
    '/currencies/dlord,raydium,3krwsxrweubpsdj9nkiwznjsxlqkdpjngzeeu5mzkkrb.png',
  'DMAGA,RAYDIUM,7D7BRCBYEPFI77VXYSAPMEQRNN1WSBBXNFPJGBH5PUMP':
    '/currencies/dmaga,raydium,7d7brcbyepfi77vxysapmeqrnn1wsbbxnfpjgbh5pump.png',
  DMTR: '/currencies/dmtr.png',
  DNT: '/currencies/dnt.png',
  DNX: '/currencies/dnx.png',
  DOAI: '/currencies/doai.png',
  'DOAI,RAYDIUM,3VMFEATR9M2PP5JCFNC8C8U6U4EFUBDQ6FQJGPPCNFKS':
    '/currencies/doai,raydium,3vmfeatr9m2pp5jcfnc8c8u6u4efubdq6fqjgppcnfks.png',
  'DOG,UNISWAP_V3,0XBAAC2B4491727D78D2B78815144570B9F2FE8899':
    '/currencies/dog,uniswap_v3,0xbaac2b4491727d78d2b78815144570b9f2fe8899.png',
  'DOKY,RAYDIUM,5RS53FY3Q4T4MLK9ZBQ45CVNGF1RH7NQRNXIP6PA5RYH':
    '/currencies/doky,raydium,5rs53fy3q4t4mlk9zbq45cvngf1rh7nqrnxip6pa5ryh.png',
  'DOLLAR,RAYDIUM,5ANPDX9GPOSBI9JSW2DFFE5QQD3FMXBUDOQUMNDXPUMP':
    '/currencies/dollar,raydium,5anpdx9gposbi9jsw2dffe5qqd3fmxbudoqumndxpump.png',
  DOME: '/currencies/dome.png',
  'DOOGLE,RAYDIUM,F6TSRCJTLBZKDTZYQJTPVQ9WTNWHMMC1WCQGUEGCPUMP':
    '/currencies/doogle,raydium,f6tsrcjtlbzkdtzyqjtpvq9wtnwhmmc1wcqguegcpump.png',
  'DOUG,RAYDIUM,BAVUJ8BNTC79A8AHTXQI1EUHCCNQVEU8KSBE4SVCAAHC':
    '/currencies/doug,raydium,bavuj8bntc79a8ahtxqi1euhccnqveu8ksbe4svcaahc.png',
  DPX: '/currencies/dpx.png',
  DSYNC: '/currencies/dsync.png',
  'DSYNC,UNISWAP_V3,0XF94E7D0710709388BCE3161C32B4EEA56D3F91CC':
    '/currencies/dsync,uniswap_v3,0xf94e7d0710709388bce3161c32b4eea56d3f91cc.png',
  DTEC: '/currencies/dtec.png',
  DUEL: '/currencies/duel.png',
  'DUKO,RAYDIUM,HLPTM5E6RTGH4EKGDPYFRNRHBJPKMYVDEEREEA2G7RF9':
    '/currencies/duko,raydium,hlptm5e6rtgh4ekgdpyfrnrhbjpkmyvdeereea2g7rf9.png',
  DUST: '/currencies/dust.png',
  DZOO: '/currencies/dzoo.png',
  'EBULL,UNISWAP_V3,0X71297312753EA7A2570A5A3278ED70D9A75F4F44':
    '/currencies/ebull,uniswap_v3,0x71297312753ea7a2570a5a3278ed70d9a75f4f44.png',
  'EGL,RAYDIUM,DCCA1IVQRYFQWSQTZ3ARKFKPD6UXV6AN8JDW5S3EVKQZ':
    '/currencies/egl,raydium,dcca1ivqryfqwsqtz3arkfkpd6uxv6an8jdw5s3evkqz.png',
  EGP: '/currencies/egp.png',
  EIGEN: '/currencies/eigen.png',
  ELDA: '/currencies/elda.png',
  ELIX: '/currencies/elix.png',
  EMT: '/currencies/emt.png',
  'EPIK,RAYDIUM,3BGWJ8B7B9HHX4SGFZ2KJHV9496COVFSMK2YEPEVSBRW':
    '/currencies/epik,raydium,3bgwj8b7b9hhx4sgfz2kjhv9496covfsmk2yepevsbrw.png',
  EPX: '/currencies/epx.png',
  EVMOS: '/currencies/evmos.png',
  'EXGO,RAYDIUM,D5YMUBHSVOVYKAGUCGKNK2CM8UYGKTNTXJ62T3C46NXS':
    '/currencies/exgo,raydium,d5ymubhsvovykagucgknk2cm8uygktntxj62t3c46nxs.png',
  EXVG: '/currencies/exvg.png',
  'FALX,RAYDIUM,AFO4NUMBNHDXC7M7P6QJZ1PF3LBQYFG5K1CNRGVE8RVU':
    '/currencies/falx,raydium,afo4numbnhdxc7m7p6qjz1pf3lbqyfg5k1cnrgve8rvu.png',
  FAME: '/currencies/fame.png',
  FAR: '/currencies/far.png',
  FB: '/currencies/fb.png',
  FDUSD: '/currencies/fdusd.png',
  FIGHT: '/currencies/fight.png',
  FLT: '/currencies/flt.png',
  'FLT,UNISWAP_V3,0X236501327E701692A281934230AF0B6BE8DF3353':
    '/currencies/flt,uniswap_v3,0x236501327e701692a281934230af0b6be8df3353.png',
  'FLUFFI,RAYDIUM,6CEJCG7JO5RV9KFSGKX66RPW19NRSCMCCD2BXFWPUMP':
    '/currencies/fluffi,raydium,6cejcg7jo5rv9kfsgkx66rpw19nrscmccd2bxfwpump.png',
  FMB: '/currencies/fmb.png',
  FOFAR: '/currencies/fofar.png',
  FON: '/currencies/fon.png',
  FOX: '/currencies/fox.png',
  FREE: '/currencies/free.png',
  FTR: '/currencies/ftr.png',
  FUN: '/currencies/fun.png',
  'FUN,UNISWAP_V3,0X419D0D8BDD9AF5E606AE2232ED285AFF190E711B':
    '/currencies/fun,uniswap_v3,0x419d0d8bdd9af5e606ae2232ed285aff190e711b.png',
  FUSE: '/currencies/fuse.png',
  GALAXIS: '/currencies/galaxis.png',
  GAT: '/currencies/gat.png',
  GEAR: '/currencies/gear.png',
  GEMS: '/currencies/gems.png',
  GENE: '/currencies/gene.png',
  GEOD: '/currencies/geod.png',
  GFI: '/currencies/gfi.png',
  'GIGA,RAYDIUM,63LFDMNB3MQ8MW9MTZ2TO9BEA2M71KZUUGQ5TIJXCQJ9':
    '/currencies/giga,raydium,63lfdmnb3mq8mw9mtz2to9bea2m71kzuugq5tijxcqj9.png',
  'GIKO,RAYDIUM,3WPEP4UFATOK1AS5S8BL9INZEURT4DYAQCIIC6ZKKC1U':
    '/currencies/giko,raydium,3wpep4ufatok1as5s8bl9inzeurt4dyaqciic6zkkc1u.png',
  'GINNAN,RAYDIUM,GINNABFFZL4FUJ9VACTXHA74GDAW8KDPGAHQMTMZPS2F':
    '/currencies/ginnan,raydium,ginnabffzl4fuj9vactxha74gdaw8kdpgahqmtmzps2f.png',
  GLQ: '/currencies/glq.png',
  'GME,RAYDIUM,8WXTPEU6557ETKP9WHFY1N1ECU6NXDVBAGGHGSMYIHSB':
    '/currencies/gme,raydium,8wxtpeu6557etkp9whfy1n1ecu6nxdvbagghgsmyihsb.png',
  'GNUS,UNISWAP_V3,0X614577036F0A024DBC1C88BA616B394DD65D105A':
    '/currencies/gnus,uniswap_v3,0x614577036f0a024dbc1c88ba616b394dd65d105a.png',
  'GOAT,RAYDIUM,59U8QAD2S2GETSY5VS7DJ95YSPNHAVYHETRFZCEB9F7G':
    '/currencies/goat,raydium,59u8qad2s2getsy5vs7dj95yspnhavyhetrfzceb9f7g.png',
  GOG: '/currencies/gog.png',
  GPT: '/currencies/gpt.png',
  GRND: '/currencies/grnd.png',
  GROK: '/currencies/grok.png',
  GSWIFT: '/currencies/gswift.png',
  'GUAC,RAYDIUM,AZSHEMXD36BJ1EMNXHOWJAJPUXZRKCK57WW4ZGXVA7YR':
    '/currencies/guac,raydium,azshemxd36bj1emnxhowjajpuxzrkck57ww4zgxva7yr.png',
  'GURU,UNISWAP_V3,0X525574C899A7C877A11865339E57376092168258':
    '/currencies/guru,uniswap_v3,0x525574c899a7c877a11865339e57376092168258.png',
  'HABIBI,RAYDIUM,864YJRB3JAVARC4FNUDTPKFXDESYRBB39NWXKZUDXY46':
    '/currencies/habibi,raydium,864yjrb3javarc4fnudtpkfxdesyrbb39nwxkzudxy46.png',
  HAI: '/currencies/hai.png',
  'HAMI,RAYDIUM,4SP2EUDRQF46RZUN6SYAWZJRXWUPX2T3NJUOKMV766RJ':
    '/currencies/hami,raydium,4sp2eudrqf46rzun6syawzjrxwupx2t3njuokmv766rj.png',
  'HAMMY,RAYDIUM,26KMQVGDUOB6REFNJ51YAABWWJND8UMTPNQGSHQ64UDR':
    '/currencies/hammy,raydium,26kmqvgduob6refnj51yaabwwjnd8umtpnqgshq64udr.png',
  'HARAMBE,RAYDIUM,FCH1OIXTPRI8ZXBNMDCEADOJW2TOYFHXQDZACQKWDVSP':
    '/currencies/harambe,raydium,fch1oixtpri8zxbnmdceadojw2toyfhxqdzacqkwdvsp.png',
  'HARRIS,UNISWAP_V3,0X155788DD4B3CCD955A5B2D461C7D6504F83F71FA':
    '/currencies/harris,uniswap_v3,0x155788dd4b3ccd955a5b2d461c7d6504f83f71fa.png',
  'HAWKTUAH,RAYDIUM,4GFE6MBDORSY5BLBIUMRGETR6PZCJYFXMDM5EHSGPUMP':
    '/currencies/hawktuah,raydium,4gfe6mbdorsy5blbiumrgetr6pzcjyfxmdm5ehsgpump.png',
  HEART: '/currencies/heart.png',
  'HEGE,RAYDIUM,ULWSJMMPXMNRFPU6BJNK6RPRKXQD5JXUMPPS1FXHXFY':
    '/currencies/hege,raydium,ulwsjmmpxmnrfpu6bjnk6rprkxqd5jxumpps1fxhxfy.png',
  'HEHE,RAYDIUM,BREUHVOHXX5FV6Q41UYB3SOJTAUGOGAIAHKBMTCRPUMP':
    '/currencies/hehe,raydium,breuhvohxx5fv6q41uyb3sojtaugogaiahkbmtcrpump.png',
  HELLO: '/currencies/hello.png',
  'HEX,UNISWAP_V3,0X2B591E99AFE9F32EAA6214F7B7629768C40EEB39':
    '/currencies/hex,uniswap_v3,0x2b591e99afe9f32eaa6214f7b7629768c40eeb39.png',
  HGPT: '/currencies/hgpt.png',
  HMND: '/currencies/hmnd.png',
  HMSTR: '/currencies/hmstr.png',
  'HOGE,RAYDIUM,74GUPK636NRIEDT9KLSGF1PEWG5BB7ITNKJF2BKMDWZJ':
    '/currencies/hoge,raydium,74gupk636nriedt9klsgf1pewg5bb7itnkjf2bkmdwzj.png',
  HONEY: '/currencies/honey.png',
  'HONK,RAYDIUM,3AG1MJ9AKZ9FAKCQ6GAEHPLSX8B2PUBPDKB9IBSDLZNB':
    '/currencies/honk,raydium,3ag1mj9akz9fakcq6gaehplsx8b2pubpdkb9ibsdlznb.png',
  HOPR: '/currencies/hopr.png',
  'HUND,RAYDIUM,2XPQOKFJITK8YCMDGBKY7CMZRRYF2X9PNIZECYKDUZEV':
    '/currencies/hund,raydium,2xpqokfjitk8ycmdgbky7cmzrryf2x9pnizecykduzev.png',
  'HUNT,UNISWAP_V3,0X9AAB071B4129B083B01CB5A0CB513CE7ECA26FA5':
    '/currencies/hunt,uniswap_v3,0x9aab071b4129b083b01cb5a0cb513ce7eca26fa5.png',
  HVH: '/currencies/hvh.png',
  HYDRA: '/currencies/hydra.png',
  IDRT: '/currencies/idrt.png',
  'IMPT,UNISWAP_V3,0X04C17B9D3B29A78F7BD062A57CF44FC633E71F85':
    '/currencies/impt,uniswap_v3,0x04c17b9d3b29a78f7bd062a57cf44fc633e71f85.png',
  INDEX: '/currencies/index.png',
  INV: '/currencies/inv.png',
  'IOT,RAYDIUM,IOTEVVZLEYWOTN1QDWNPDDXPWSZN3ZFHEOT3MFL9FNS':
    '/currencies/iot,raydium,iotevvzleywotn1qdwnpddxpwszn3zfheot3mfl9fns.png',
  IQ50: '/currencies/iq50.png',
  'IQ50,RAYDIUM,21RWEMLGYEMNONHW7H3XA5PY17X6ZFRCHIRCP9INRBQA':
    '/currencies/iq50,raydium,21rwemlgyemnonhw7h3xa5py17x6zfrchircp9inrbqa.png',
  IRIS: '/currencies/iris.png',
  IRON: '/currencies/iron.png',
  ISLM: '/currencies/islm.png',
  ISP: '/currencies/isp.png',
  'JASON,RAYDIUM,6SURYVEUDZ5HQAXAB6QRGFBZWVJN8DC7M29EZSVDPUMP':
    '/currencies/jason,raydium,6suryveudz5hqaxab6qrgfbzwvjn8dc7m29ezsvdpump.png',
  JUICE: '/currencies/juice.png',
  JUM: '/currencies/jum.png',
  'JUNGLE,RAYDIUM,9P32YQUCXFZNDOXMMJNZBPQXQGFOU4TA4SB1RAQH9CYW':
    '/currencies/jungle,raydium,9p32yqucxfzndoxmmjnzbpqxqgfou4ta4sb1raqh9cyw.png',
  'KAMA,RAYDIUM,HNKKZR1YTFBUUXM6G3IVRS2RY68KHHGV7BNDFF1GCSJB':
    '/currencies/kama,raydium,hnkkzr1ytfbuuxm6g3ivrs2ry68khhgv7bndff1gcsjb.png',
  KASTA: '/currencies/kasta.png',
  'KHAI,RAYDIUM,3TWGDVYBL2YPET2LXNWAWSMEOA8AL4DUTNUWAT2PKCJC':
    '/currencies/khai,raydium,3twgdvybl2ypet2lxnwawsmeoa8al4dutnuwat2pkcjc.png',
  KISHU: '/currencies/kishu.png',
  'KITTENWIF,RAYDIUM,9A8AMDFQXFJ44RRVHKDIXNKWCWT99IGWP5QRRUC73PIN':
    '/currencies/kittenwif,raydium,9a8amdfqxfj44rrvhkdixnkwcwt99igwp5qrruc73pin.png',
  'KIZUNA,UNISWAP_V3,0X470C8950C0C3AA4B09654BC73B004615119A44B5':
    '/currencies/kizuna,uniswap_v3,0x470c8950c0c3aa4b09654bc73b004615119a44b5.png',
  KMON: '/currencies/kmon.png',
  KNINE: '/currencies/knine.png',
  'KOKO,RAYDIUM,FSA54YL49WKS7RWOGV9SUCBSGWCWV756JTD349E6H2YW':
    '/currencies/koko,raydium,fsa54yl49wks7rwogv9sucbsgwcwv756jtd349e6h2yw.png',
  KON: '/currencies/kon.png',
  'LABZ,RAYDIUM,4VC7UYQBO9SIW8ZNKPXFW9D3DZYCIVRPDZS9XRTYRJMH':
    '/currencies/labz,raydium,4vc7uyqbo9siw8znkpxfw9d3dzycivrpdzs9xrtyrjmh.png',
  'LADYF,RAYDIUM,3X8GCLIH2HTTJYQEPG7MAZPMBWBGQ5URUMTYDZ5TKMDE':
    '/currencies/ladyf,raydium,3x8gclih2httjyqepg7mazpmbwbgq5urumtydz5tkmde.png',
  'LAIKA,RAYDIUM,EUOQ6CYQFCJCVSLR9WFAUPDW19Y6ZHWECJOZSEI643I1':
    '/currencies/laika,raydium,euoq6cyqfcjcvslr9wfaupdw19y6zhwecjozsei643i1.png',
  LAND: '/currencies/land.png',
  LAZIO: '/currencies/lazio.png',
  LEO: '/currencies/leo.png',
  'LFGO,RAYDIUM,2U98MM7DMTVMNG4IAKRNMTYNJMKZGD6FXAZB3WVFHQVG':
    '/currencies/lfgo,raydium,2u98mm7dmtvmng4iakrnmtynjmkzgd6fxazb3wvfhqvg.png',
  'LIBERTA,RAYDIUM,EGQCDSZVIK6T1DHCAGJBVFTC9CD4AQIRIHZWEHYQ84LG':
    '/currencies/liberta,raydium,egqcdszvik6t1dhcagjbvftc9cd4aqirihzwehyq84lg.png',
  'LILPUMP,RAYDIUM,9VRGUHWSC8LYLJQOH3ZJB9S53X7A88U49LA63QPB6F5T':
    '/currencies/lilpump,raydium,9vrguhwsc8lyljqoh3zjb9s53x7a88u49la63qpb6f5t.png',
  LIME: '/currencies/lime.png',
  LIS: '/currencies/lis.png',
  'LIT,UNISWAP_V3,0XFD0205066521550D7D7AB19DA8F72BB004B4C341':
    '/currencies/lit,uniswap_v3,0xfd0205066521550d7d7ab19da8f72bb004b4c341.png',
  LKI: '/currencies/lki.png',
  LMR: '/currencies/lmr.png',
  'LMR,UNISWAP_V3,0X4B1D0B9F081468D780CA1D5D79132B64301085D1':
    '/currencies/lmr,uniswap_v3,0x4b1d0b9f081468d780ca1d5d79132b64301085d1.png',
  LOBO: '/currencies/lobo.png',
  LOCUS: '/currencies/locus.png',
  'LOS,RAYDIUM,44BZGE9EZJGPJRYNMSA64MDKZ1EELDDCDICZRMOYATEZ':
    '/currencies/los,raydium,44bzge9ezjgpjrynmsa64mdkz1eelddcdiczrmoyatez.png',
  'LOVE,RAYDIUM,4QQV4LQUUXAN1EN1XQGRFY65TFLE5STJCFSCQOZQYB8T':
    '/currencies/love,raydium,4qqv4lquuxan1en1xqgrfy65tfle5stjcfscqozqyb8t.png',
  LSETH: '/currencies/lseth.png',
  LUNA: '/currencies/luna.png',
  LUNC: '/currencies/lunc.png',
  'MAD,RAYDIUM,MADHPJRN6BD8T78RSY7NUSUNWWA2HU8BYPOBZPRHBHV':
    '/currencies/mad,raydium,madhpjrn6bd8t78rsy7nusunwwa2hu8bypobzprhbhv.png',
  MAGA: '/currencies/maga.png',
  MAK: '/currencies/mak.png',
  MAN: '/currencies/man.png',
  'MARS,UNISWAP_V3,0XB8D6196D71CDD7D90A053A7769A077772AAAC464':
    '/currencies/mars,uniswap_v3,0xb8d6196d71cdd7d90a053a7769a077772aaac464.png',
  MARSH: '/currencies/marsh.png',
  'MASQ,UNISWAP_V3,0X06F3C323F0238C72BF35011071F2B5B7F43A054C':
    '/currencies/masq,uniswap_v3,0x06f3c323f0238c72bf35011071f2b5b7f43a054c.png',
  MATH: '/currencies/math.png',
  MBS: '/currencies/mbs.png',
  MCG: '/currencies/mcg.png',
  MDAO: '/currencies/mdao.png',
  'MDT,RAYDIUM,8WQBST4QAN2FQBCCH5GDXQ2WJ7VTNWEY4ONLRPUG7TYA':
    '/currencies/mdt,raydium,8wqbst4qan2fqbcch5gdxq2wj7vtnwey4onlrpug7tya.png',
  MEDIA: '/currencies/media.png',
  MEE: '/currencies/mee.png',
  METH: '/currencies/meth.png',
  MFER: '/currencies/mfer.png',
  'MICHI,RAYDIUM,5MBK36SZ7J19AN8JFOCHHQS4OF8G6BWUJBECSXBSOWDP':
    '/currencies/michi,raydium,5mbk36sz7j19an8jfochhqs4of8g6bwujbecsxbsowdp.png',
  MIGGLES: '/currencies/miggles.png',
  MILO: '/currencies/milo.png',
  'MINI,RAYDIUM,2JCXACFWT9MVAWBQ5NZKYWCYXQKRCDSYRDXN6HJ22SBP':
    '/currencies/mini,raydium,2jcxacfwt9mvawbq5nzkywcyxqkrcdsyrdxn6hj22sbp.png',
  MIX: '/currencies/mix.png',
  'ML,UNISWAP_V3,0X059956483753947536204E89BFAD909E1A434CC6':
    '/currencies/ml,uniswap_v3,0x059956483753947536204e89bfad909e1a434cc6.png',
  MLT: '/currencies/mlt.png',
  MNW: '/currencies/mnw.png',
  MOB: '/currencies/mob.png',
  MOCA: '/currencies/moca.png',
  MODE: '/currencies/mode.png',
  MOJO: '/currencies/mojo.png',
  'MONGY,RAYDIUM,FSBPYIGZ4BHUXVSPP7XPJYFTPM5PSLJC2WGZAFADPUMP':
    '/currencies/mongy,raydium,fsbpyigz4bhuxvspp7xpjyftpm5psljc2wgzafadpump.png',
  'MONK,RAYDIUM,FYA25XNBSXQXADTNSYKBKD5GZ1VZHCHBRF57CQFRXJZX':
    '/currencies/monk,raydium,fya25xnbsxqxadtnsykbkd5gz1vzhchbrf57cqfrxjzx.png',
  MOODENG: '/currencies/moodeng.png',
  'MOODENG,UNISWAP_V3,0X28561B8A2360F463011C16B6CC0B0CBEF8DBBCAD':
    '/currencies/moodeng,uniswap_v3,0x28561b8a2360f463011c16b6cc0b0cbef8dbbcad.png',
  'MOUTAI,RAYDIUM,45EGCWCPXYAGBC7KQBIN4NCFGEZWN7F3Y6NACWXQMCWX':
    '/currencies/moutai,raydium,45egcwcpxyagbc7kqbin4ncfgezwn7f3y6nacwxqmcwx.png',
  MOXIE: '/currencies/moxie.png',
  MPC: '/currencies/mpc.png',
  MPT: '/currencies/mpt.png',
  MSTAR: '/currencies/mstar.png',
  'MUMU,RAYDIUM,5LAFQURVCO6O7KMZ42EQVEJ9LW31STPYGJEEU5SKOMTA':
    '/currencies/mumu,raydium,5lafqurvco6o7kmz42eqvej9lw31stpygjeeu5skomta.png',
  MUSIC: '/currencies/music.png',
  MYTH: '/currencies/myth.png',
  NADA: '/currencies/nada.png',
  'NAP,RAYDIUM,4G86CMXGSMDLETRYNAVMFKPHQZKTVDBYGMRADVTR72NU':
    '/currencies/nap,raydium,4g86cmxgsmdletrynavmfkphqzktvdbygmradvtr72nu.png',
  NCN: '/currencies/ncn.png',
  NCT: '/currencies/nct.png',
  NEER: '/currencies/neer.png',
  'NEIREI,UNISWAP_V3,0X1D4FB9BFA1967BE6CA74819E28B98C2AA5AE8B59':
    '/currencies/neirei,uniswap_v3,0x1d4fb9bfa1967be6ca74819e28b98c2aa5ae8b59.png',
  NESS: '/currencies/ness.png',
  'NEVER,RAYDIUM,CXRHHSQYW8YTDWC4CSJMMGO7UBUJSXZNZRWHTW9ULDRU':
    '/currencies/never,raydium,cxrhhsqyw8ytdwc4csjmmgo7ubujsxznzrwhtw9uldru.png',
  NEXT: '/currencies/next.png',
  'NFAI,UNISWAP_V3,0X17C50D62E6E8D20D2DC18E9AD79C43263D0720D9':
    '/currencies/nfai,uniswap_v3,0x17c50d62e6e8d20d2dc18e9ad79c43263d0720d9.png',
  NIM: '/currencies/nim.png',
  'NINJA,RAYDIUM,2XP43MAWHFU7PWPUMVKC6AUWG4GX8XPQLTGMKSZFCEJT':
    '/currencies/ninja,raydium,2xp43mawhfu7pwpumvkc6auwg4gx8xpqltgmkszfcejt.png',
  NIZA: '/currencies/niza.png',
  'NOMNOM,RAYDIUM,6ZRYHKWVOYE4QQZPDZJ7HTEHWT2U2546EKTNJ7QEPUMP':
    '/currencies/nomnom,raydium,6zryhkwvoye4qqzpdzj7htehwt2u2546ektnj7qepump.png',
  'NOS,RAYDIUM,NOSXBVOACTTYDLVKY6CSB4AC8JCDQKKAAWYTX2ZMOO7':
    '/currencies/nos,raydium,nosxbvoacttydlvky6csb4ac8jcdqkkaawytx2zmoo7.png',
  NOTAI: '/currencies/notai.png',
  NPC: '/currencies/npc.png',
  'NPCS,RAYDIUM,5TODNKIBAK6K697RRYNGTBURU7YZNFZFX7JZSD1UC7PK':
    '/currencies/npcs,raydium,5todnkibak6k697rryngtburu7yznfzfx7jzsd1uc7pk.png',
  NPT: '/currencies/npt.png',
  'NSO,RAYDIUM,HGMFSGNDLQ6VGLXCW4J33NJRWV2ZTH81IEJNVWK9KCHD':
    '/currencies/nso,raydium,hgmfsgndlq6vglxcw4j33njrwv2zth81iejnvwk9kchd.png',
  NSTR: '/currencies/nstr.png',
  'NUB,RAYDIUM,GTDZKAQVMZMNTI46ZEWMIXCA4OXF4BZXWQPOKZXPFXZN':
    '/currencies/nub,raydium,gtdzkaqvmzmnti46zewmixca4oxf4bzxwqpokzxpfxzn.png',
  NUX: '/currencies/nux.png',
  'NXRA,UNISWAP_V3,0X644192291CC835A93D6330B24EA5F5FEDD0EEF9E':
    '/currencies/nxra,uniswap_v3,0x644192291cc835a93d6330b24ea5f5fedd0eef9e.png',
  OAX: '/currencies/oax.png',
  OBI: '/currencies/obi.png',
  OCTA: '/currencies/octa.png',
  'OHM,UNISWAP_V3,0X64AA3364F17A4D01C6F1751FD97C2BD3D7E7F1D5':
    '/currencies/ohm,uniswap_v3,0x64aa3364f17a4d01c6f1751fd97c2bd3d7e7f1d5.png',
  OKT: '/currencies/okt.png',
  OMI: '/currencies/omi.png',
  OMNI: '/currencies/omni.png',
  OOKI: '/currencies/ooki.png',
  OORT: '/currencies/oort.png',
  'ORACLE,RAYDIUM,3TU6NPNDFVQNOBQKMGJDWZE1LBVE9SRUDQHSSQXWK1HL':
    '/currencies/oracle,raydium,3tu6npndfvqnobqkmgjdwze1lbve9srudqhssqxwk1hl.png',
  'ORBT,RAYDIUM,BGYJASMSZYM9HHIZ1LBU4EJ7KCTRJMSPBN4ZTRU3W5VF':
    '/currencies/orbt,raydium,bgyjasmszym9hhiz1lbu4ej7kctrjmspbn4ztru3w5vf.png',
  'ORC,RAYDIUM,CZYWQYWNZACQC7NPHTAPHC8CB2H7OU6U9TEHBRVNZJKX':
    '/currencies/orc,raydium,czywqywnzacqc7nphtaphc8cb2h7ou6u9tehbrvnzjkx.png',
  ORDER: '/currencies/order.png',
  ORDS: '/currencies/ords.png',
  ORT: '/currencies/ort.png',
  OVR: '/currencies/ovr.png',
  'OWO,UNISWAP-V3-BASE,0X5D559EA7BB2DAE4B694A079CB8328A2145FD32F6':
    '/currencies/owo,uniswap-v3-base,0x5d559ea7bb2dae4b694a079cb8328a2145fd32f6.png',
  OX: '/currencies/ox.png',
  'OXY,RAYDIUM,Z3DN17YLAGMKFFVOGEFHQ9ZWVCXGQGF3PQNDSNS2G6M':
    '/currencies/oxy,raydium,z3dn17ylagmkffvogefhq9zwvcxgqgf3pqndsns2g6m.png',
  PAAL: '/currencies/paal.png',
  'PAAL,UNISWAP_V3,0X14FEE680690900BA0CCCFC76AD70FD1B95D10E16':
    '/currencies/paal,uniswap_v3,0x14fee680690900ba0cccfc76ad70fd1b95d10e16.png',
  PACK: '/currencies/pack.png',
  'PAJAMAS,RAYDIUM,FVER7SSVY5GQAMAWF7QFB5MNUUMDDBPNPG4NCA4ZHOLW':
    '/currencies/pajamas,raydium,fver7ssvy5gqamawf7qfb5mnuumddbpnpg4nca4zholw.png',
  'PANDORA,UNISWAP_V3,0X9E9FBDE7C7A83C43913BDDC8779158F1368F0413':
    '/currencies/pandora,uniswap_v3,0x9e9fbde7c7a83c43913bddc8779158f1368f0413.png',
  PARAM: '/currencies/param.png',
  PBX: '/currencies/pbx.png',
  PCH: '/currencies/pch.png',
  'PEAS,UNISWAP_V3,0X02F92800F57BCD74066F5709F1DAA1A4302DF875':
    '/currencies/peas,uniswap_v3,0x02f92800f57bcd74066f5709f1daa1a4302df875.png',
  PEIPEI: '/currencies/peipei.png',
  'PELF,RAYDIUM,BGJW7U1U2RY5XJK9UYB5AQFRZJMTQE7PW3KAF9IW9NTZ':
    '/currencies/pelf,raydium,bgjw7u1u2ry5xjk9uyb5aqfrzjmtqe7pw3kaf9iw9ntz.png',
  PEW: '/currencies/pew.png',
  'PEW,UNISWAP_V3,0X382EA807A61A418479318EFD96F1EFBC5C1F2C21':
    '/currencies/pew,uniswap_v3,0x382ea807a61a418479318efd96f1efbc5c1f2c21.png',
  PHIL: '/currencies/phil.png',
  PIKA: '/currencies/pika.png',
  'PIP,RAYDIUM,HHJOYWUP5AU6PNRVN4S2PWEERWXNZKHXKGYJRJMOBJLW':
    '/currencies/pip,raydium,hhjoywup5au6pnrvn4s2pweerwxnzkhxkgyjrjmobjlw.png',
  PIVX: '/currencies/pivx.png',
  PIZZA: '/currencies/pizza.png',
  PLANET: '/currencies/planet.png',
  PLN: '/currencies/pln.png',
  PMG: '/currencies/pmg.png',
  PNK: '/currencies/pnk.png',
  POLK: '/currencies/polk.png',
  POLYDOGE: '/currencies/polydoge.png',
  POR: '/currencies/por.png',
  PORK: '/currencies/pork.png',
  PORT3: '/currencies/port3.png',
  PORTO: '/currencies/porto.png',
  'POS,RAYDIUM,B8VV6AN7XFF3BARB1CMU7TMFKNJJES2WVY7JWQIRC6K6':
    '/currencies/pos,raydium,b8vv6an7xff3barb1cmu7tmfknjjes2wvy7jwqirc6k6.png',
  'POWR,UNISWAP_V3,0X595832F8FC6BF59C85C527FEC3740A1B7A361269':
    '/currencies/powr,uniswap_v3,0x595832f8fc6bf59c85c527fec3740a1b7a361269.png',
  'POWSCHE,RAYDIUM,8CKISHHJDHJV4LUOIRMLUHQG58CUKBYJRTCP4Z3MCXNF':
    '/currencies/powsche,raydium,8ckishhjdhjv4luoirmluhqg58cukbyjrtcp4z3mcxnf.png',
  PPT: '/currencies/ppt.png',
  PRIMAL: '/currencies/primal.png',
  PRO: '/currencies/pro.png',
  PROPS: '/currencies/props.png',
  PROS: '/currencies/pros.png',
  PTC: '/currencies/ptc.png',
  PUGGY: '/currencies/puggy.png',
  'PUNDIX,UNISWAP_V3,0X0FD10B9899882A6F2FCB5C371E17E70FDEE00C38':
    '/currencies/pundix,uniswap_v3,0x0fd10b9899882a6f2fcb5c371e17e70fdee00c38.png',
  'PUNDU,RAYDIUM,WSKZSKQEW3ZSMRHPAEVFVZB6PUULZWOV9MJWZSFDEPC':
    '/currencies/pundu,raydium,wskzskqew3zsmrhpaevfvzb6puulzwov9mjwzsfdepc.png',
  PURSE: '/currencies/purse.png',
  'PZP,RAYDIUM,2CNFY3WZU715MDBJ1CEWFMNCSKNQKREPJTMW4O1PSJ9J':
    '/currencies/pzp,raydium,2cnfy3wzu715mdbj1cewfmncsknqkrepjtmw4o1psj9j.png',
  QANX: '/currencies/qanx.png',
  QUBIC: '/currencies/qubic.png',
  QUICK: '/currencies/quick.png',
  RADAR: '/currencies/radar.png',
  'RADX,RAYDIUM,FVFZXEEWZRXOOU8N8PJGPWKHHZOUDJPFW6RZVAEXQGVY':
    '/currencies/radx,raydium,fvfzxeewzrxoou8n8pjgpwkhhzoudjpfw6rzvaexqgvy.png',
  RAIN: '/currencies/rain.png',
  RATS: '/currencies/rats.png',
  'RBT,RAYDIUM,65NTNUJGHME4PQVKQYJYKKP1BJAKK4A8Q66SD2YBWUGF':
    '/currencies/rbt,raydium,65ntnujghme4pqvkqyjykkp1bjakk4a8q66sd2ybwugf.png',
  REAL: '/currencies/real.png',
  REDO: '/currencies/redo.png',
  'RETARDIO,RAYDIUM,6OGZHHZDRQR9PGV6HZ2MNZE7URZBMAFYBBWUYP1FHITX':
    '/currencies/retardio,raydium,6ogzhhzdrqr9pgv6hz2mnze7urzbmafybbwuyp1fhitx.png',
  'RETH,UNISWAP_V3,0XAE78736CD615F374D3085123A210448E74FC6393':
    '/currencies/reth,uniswap_v3,0xae78736cd615f374d3085123a210448e74fc6393.png',
  RFRM: '/currencies/rfrm.png',
  RITE: '/currencies/rite.png',
  RJV: '/currencies/rjv.png',
  'RLB,UNISWAP_V3,0X046EEE2CC3188071C02BFC1745A6B17C656E3F3D':
    '/currencies/rlb,uniswap_v3,0x046eee2cc3188071c02bfc1745a6b17c656e3f3d.png',
  'RNT,RAYDIUM,2FUFHZYD47MAPV9WCFXH5GNQWFXTQCYU9XAN4THBPUMP':
    '/currencies/rnt,raydium,2fufhzyd47mapv9wcfxh5gnqwfxtqcyu9xan4thbpump.png',
  ROA: '/currencies/roa.png',
  'ROA,RAYDIUM,5TB5D6DGJMXXHYMNKFJNG237X6PZGEWTZGPUUH62YQJ7':
    '/currencies/roa,raydium,5tb5d6dgjmxxhymnkfjng237x6pzgewtzgpuuh62yqj7.png',
  'RODAI,RAYDIUM,GDBYLSNKHKLXTZVEO8QRGKVMREXEEZUYVHPSFUZ9TDKC':
    '/currencies/rodai,raydium,gdbylsnkhklxtzveo8qrgkvmrexeezuyvhpsfuz9tdkc.png',
  RON: '/currencies/ron.png',
  ROND: '/currencies/rond.png',
  RPK: '/currencies/rpk.png',
  'RSC,UNISWAP_V3,0XD101DCC414F310268C37EEB4CD376CCFA507F571':
    '/currencies/rsc,uniswap_v3,0xd101dcc414f310268c37eeb4cd376ccfa507f571.png',
  RUNECOIN: '/currencies/runecoin.png',
  SAI: '/currencies/sai.png',
  SAKAI: '/currencies/sakai.png',
  SALD: '/currencies/sald.png',
  SANTOS: '/currencies/santos.png',
  'SATO,UNISWAP_V3,0X5DE758BBA013E58DAE2693AEA3F0B12B31A3023D':
    '/currencies/sato,uniswap_v3,0x5de758bba013e58dae2693aea3f0b12b31a3023d.png',
  SAUCE: '/currencies/sauce.png',
  'SB,RAYDIUM,8TWUNZMSZQWEFBDERWTF4GW13E6MUS4HSDX5MI3AQXAM':
    '/currencies/sb,raydium,8twunzmszqwefbderwtf4gw13e6mus4hsdx5mi3aqxam.png',
  'SBABE,RAYDIUM,D9MFKGNZHNQGRTZKVNJ44YVOLTJMFBZRAHXIUKCAZRE4':
    '/currencies/sbabe,raydium,d9mfkgnzhnqgrtzkvnj44yvoltjmfbzrahxiukcazre4.png',
  'SBAE,RAYDIUM,BWWWURBODJGBOVFETC3FC6OSBQKDOE62E1XQZ7X4PUMP':
    '/currencies/sbae,raydium,bwwwurbodjgbovfetc3fc6osbqkdoe62e1xqz7x4pump.png',
  'SCF,RAYDIUM,GIG7HR61RVM4CSUXJMGICOYSFQTDIWXTQF64MSRPPUMP':
    '/currencies/scf,raydium,gig7hr61rvm4csuxjmgicoysfqtdiwxtqf64msrppump.png',
  SCLP: '/currencies/sclp.png',
  SCPT: '/currencies/scpt.png',
  SDEX: '/currencies/sdex.png',
  SEAL: '/currencies/seal.png',
  SEILOR: '/currencies/seilor.png',
  'SELFIE,RAYDIUM,9WPTUKH8FKUCNEPRWOPYLH3AK9GSJPHFDENBQ2X1CZDP':
    '/currencies/selfie,raydium,9wptukh8fkucneprwopylh3ak9gsjphfdenbq2x1czdp.png',
  SEOR: '/currencies/seor.png',
  SERO: '/currencies/sero.png',
  SERSH: '/currencies/sersh.png',
  SHDW: '/currencies/shdw.png',
  'SHDW,RAYDIUM,SHDWYBXIHQICJ6YEKG2GUR7WQKLELAMK1GHZCK9PL6Y':
    '/currencies/shdw,raydium,shdwybxihqicj6yekg2gur7wqklelamk1ghzck9pl6y.png',
  SHILL: '/currencies/shill.png',
  'SHOG,UNISWAP_V3,0XC8388E437031B09B2C61FC4277469091382A1B13':
    '/currencies/shog,uniswap_v3,0xc8388e437031b09b2c61fc4277469091382a1b13.png',
  SHPING: '/currencies/shping.png',
  SHR: '/currencies/shr.png',
  'SIGMA,RAYDIUM,5SVG3T9CNQSM2KEWZBRQ6HASQH1OGFJQTTLXYUIBPUMP':
    '/currencies/sigma,raydium,5svg3t9cnqsm2kewzbrq6hasqh1ogfjqttlxyuibpump.png',
  'SKBDI,RAYDIUM,DPAQFQ5SFNOQW2SH9WMMMASFL9LNU6RDTDQWE1TAB2TB':
    '/currencies/skbdi,raydium,dpaqfq5sfnoqw2sh9wmmmasfl9lnu6rdtdqwe1tab2tb.png',
  SKEY: '/currencies/skey.png',
  'SKID,RAYDIUM,9X2RHTKRBZW3SLYE9E88CBD1KZ5RFU1F4JTSN4ARH43D':
    '/currencies/skid,raydium,9x2rhtkrbzw3slye9e88cbd1kz5rfu1f4jtsn4arh43d.png',
  SLF: '/currencies/slf.png',
  'SLIM,RAYDIUM,XXXXA1SKNGWFTW2KFN8XAUW9XQ8HBZ5KVTCSESTT9FW':
    '/currencies/slim,raydium,xxxxa1skngwftw2kfn8xauw9xq8hbz5kvtcsestt9fw.png',
  SLN: '/currencies/sln.png',
  'SLOTH,RAYDIUM,HQ7DAOIUXZC2K1DR7KXRHCCNTXVEYGNVOUEXTXE8DMBH':
    '/currencies/sloth,raydium,hq7daoiuxzc2k1dr7kxrhccntxveygnvouextxe8dmbh.png',
  SMH: '/currencies/smh.png',
  'SMILEK,RAYDIUM,7X4FGIFFEQZS1TIUNVJZPT47GTLXAJ8JFN8G1HYYU6JH':
    '/currencies/smilek,raydium,7x4fgiffeqzs1tiunvjzpt47gtlxaj8jfn8g1hyyu6jh.png',
  'SMOG,RAYDIUM,FS66V5XYTJAFO14LIPZ5HT93EUMAHMYIPCFQHLPU4SS8':
    '/currencies/smog,raydium,fs66v5xytjafo14lipz5ht93eumahmyipcfqhlpu4ss8.png',
  'SMOLE,RAYDIUM,9TTYEZ3XIRUYJ6CQAR495HBBKJU6SUWDV6AMQ9MVBYYS':
    '/currencies/smole,raydium,9ttyez3xiruyj6cqar495hbbkju6suwdv6amq9mvbyys.png',
  'SMT,UNISWAP_V3,0XB17548C7B510427BAAC4E267BEA62E800B247173':
    '/currencies/smt,uniswap_v3,0xb17548c7b510427baac4e267bea62e800b247173.png',
  SNC: '/currencies/snc.png',
  SNS: '/currencies/sns.png',
  'SNSY,UNISWAP_V3,0X82A605D6D9114F4AD6D5EE461027477EEED31E34':
    '/currencies/snsy,uniswap_v3,0x82a605d6d9114f4ad6d5ee461027477eeed31e34.png',
  'SNT,UNISWAP_V3,0X744D70FDBE2BA4CF95131626614A1763DF805B9E':
    '/currencies/snt,uniswap_v3,0x744d70fdbe2ba4cf95131626614a1763df805b9e.png',
  SOCIAL: '/currencies/social.png',
  'SOLAMA,RAYDIUM,AVLHAHDCDQ4M4VHM4UG63OH7XC8JTK49DM5HOE9SAZQR':
    '/currencies/solama,raydium,avlhahdcdq4m4vhm4ug63oh7xc8jtk49dm5hoe9sazqr.png',
  'SOLCAT,RAYDIUM,E99FN4TCRB1TQPHXK1DU7PRXJI6HMZXETYPNJRO19FWZ':
    '/currencies/solcat,raydium,e99fn4tcrb1tqphxk1du7prxji6hmzxetypnjro19fwz.png',
  'SOLCEX,RAYDIUM,AMJZRN1TBQWQFNAJHFEBB7UGBBQBJB7FZXANGGDFPK6K':
    '/currencies/solcex,raydium,amjzrn1tbqwqfnajhfebb7ugbbqbjb7fzxanggdfpk6k.png',
  'SOLS,RAYDIUM,2WME8EVKW8QSFSK2B3QEX4S64AC6WXHPXB3GRDCKEKIO':
    '/currencies/sols,raydium,2wme8evkw8qsfsk2b3qex4s64ac6wxhpxb3grdckekio.png',
  'SOLZILLA,RAYDIUM,31IQSAHFA4CMIIRU7REYGBZUAWG4R4AH7Y4ADU9ZFXJP':
    '/currencies/solzilla,raydium,31iqsahfa4cmiiru7reygbzuawg4r4ah7y4adu9zfxjp.png',
  'SOY,RAYDIUM,4G3KNXWAA2UQHDPAQTJWQM1SREXCUD7LKT14V2OES7RV':
    '/currencies/soy,raydium,4g3knxwaa2uqhdpaqtjwqm1srexcud7lkt14v2oes7rv.png',
  SPARKLET: '/currencies/sparklet.png',
  SPEC: '/currencies/spec.png',
  'SPIKE,RAYDIUM,SPIKEYAQOAGYYBANPXRO8NLSYLU93SR56N352JJRLN5':
    '/currencies/spike,raydium,spikeyaqoagyybanpxro8nlsylu93sr56n352jjrln5.png',
  SPURS: '/currencies/spurs.png',
  'SPWN,RAYDIUM,5U9QQCPHQXAJCEV9UYZFJD5ZHN93VUPK1ANNKXNUFPNT':
    '/currencies/spwn,raydium,5u9qqcphqxajcev9uyzfjd5zhn93vupk1annkxnufpnt.png',
  'SPX,RAYDIUM,J3NKXXXZCNNIMJKW9HYB2K4LUXGWB6T1FTPTQVSV3KFR':
    '/currencies/spx,raydium,j3nkxxxzcnnimjkw9hyb2k4luxgwb6t1ftptqvsv3kfr.png',
  'SRM,RAYDIUM,SRMUAPVNDXXOKK5GT7XD5CUUGXMBCOAZ2LHEUAOKWRT':
    '/currencies/srm,raydium,srmuapvndxxokk5gt7xd5cuugxmbcoaz2lheuaokwrt.png',
  SSWP: '/currencies/sswp.png',
  STAR: '/currencies/star.png',
  'STASH,RAYDIUM,EWMFSJGDCE7CXDAYZ3HBCAA7NSFHTNDDYSXX3SHCO2HS':
    '/currencies/stash,raydium,ewmfsjgdce7cxdayz3hbcaa7nsfhtnddysxx3shco2hs.png',
  'STEP,RAYDIUM,STEPASCQOEIOFXXWGNH2SLBDFP9D8RVKZ2YP39IDPYT':
    '/currencies/step,raydium,stepascqoeiofxxwgnh2slbdfp9d8rvkz2yp39idpyt.png',
  STETH: '/currencies/steth.png',
  STIK: '/currencies/stik.png',
  STMX: '/currencies/stmx.png',
  STOC: '/currencies/stoc.png',
  'STOG,RAYDIUM,AHNZ7VYYQ5JHXBITQL8TUN7CIGG66EVCNU7EKOKX99FZ':
    '/currencies/stog,raydium,ahnz7vyyq5jhxbitql8tun7cigg66evcnu7ekokx99fz.png',
  STT: '/currencies/stt.png',
  SUNCAT: '/currencies/suncat.png',
  'SUSDE,UNISWAP_V3,0X9D39A5DE30E57443BFF2A8307A4256C8797A3497':
    '/currencies/susde,uniswap_v3,0x9d39a5de30e57443bff2a8307a4256c8797a3497.png',
  SVL: '/currencies/svl.png',
  SWCH: '/currencies/swch.png',
  'SWITCH,UNISWAP_V3,0XB10CC888CB2CCE7036F4C7ECAD8A57DA16161338':
    '/currencies/switch,uniswap_v3,0xb10cc888cb2cce7036f4c7ecad8a57da16161338.png',
  'SYP,RAYDIUM,FNKE9N6AGJQONWRBZXY4RW6LZVAO7QWBONUBID7EDUMZ':
    '/currencies/syp,raydium,fnke9n6agjqonwrbzxy4rw6lzvao7qwbonubid7edumz.png',
  TADA: '/currencies/tada.png',
  TAI: '/currencies/tai.png',
  TAKI: '/currencies/taki.png',
  TAP: '/currencies/tap.png',
  TARA: '/currencies/tara.png',
  TET: '/currencies/tet.png',
  TKO: '/currencies/tko.png',
  'TMANIA,RAYDIUM,HUPSPKKI5QDNF5WAU7JTETHKEMHNI6XQ23TUNZRKZWUI':
    '/currencies/tmania,raydium,hupspkki5qdnf5wau7jtethkemhni6xq23tunzrkzwui.png',
  TOKEN: '/currencies/token.png',
  'TOOKER,RAYDIUM,9EYSCPIYSGNEIMNQPZAZR7JN9GVFXFYZGTEJ85HV9L6U':
    '/currencies/tooker,raydium,9eyscpiysgneimnqpzazr7jn9gvfxfyzgtej85hv9l6u.png',
  'TORSY,RAYDIUM,5YQCKGEKWHJMP9LW5AUF2UJRDUBMJAHCYNGJA8M7EBW8':
    '/currencies/torsy,raydium,5yqckgekwhjmp9lw5auf2ujrdubmjahcyngja8m7ebw8.png',
  TOX: '/currencies/tox.png',
  TRADE: '/currencies/trade.png',
  TRC: '/currencies/trc.png',
  'TREMP,RAYDIUM,FU1Q8VJPZNURMQSCISJP8BAKKIDGSLMOUB8CBDF8TKQV':
    '/currencies/tremp,raydium,fu1q8vjpznurmqscisjp8bakkidgslmoub8cbdf8tkqv.png',
  TRIAS: '/currencies/trias.png',
  TROLL: '/currencies/troll.png',
  TROY: '/currencies/troy.png',
  'TRUF,UNISWAP_V3,0X38C2A4A7330B22788374B8FF70BBA513C8D848CA':
    '/currencies/truf,uniswap_v3,0x38c2a4a7330b22788374b8ff70bba513c8d848ca.png',
  'TRUMP,UNISWAP-V3-BASE,0X57F5FBD3DE65DFC0BD3630F732969E5FB97E6D37':
    '/currencies/trump,uniswap-v3-base,0x57f5fbd3de65dfc0bd3630f732969e5fb97e6d37.png',
  TRUMPCOIN: '/currencies/trumpcoin.png',
  UAH: '/currencies/uah.png',
  UDS: '/currencies/uds.png',
  'UFO,RAYDIUM,99MYNE1MVNSSV2KAKZZDFNNWF5XB4SASJNACRXDBPUMP':
    '/currencies/ufo,raydium,99myne1mvnssv2kakzzdfnnwf5xb4sasjnacrxdbpump.png',
  ULD: '/currencies/uld.png',
  UPC: '/currencies/upc.png',
  'UPDOG,RAYDIUM,HJ39RRZ6YS22KDB3USXDGNSL7RKIQMSC3YL8AS3SUUKU':
    '/currencies/updog,raydium,hj39rrz6ys22kdb3usxdgnsl7rkiqmsc3yl8as3suuku.png',
  'USA,RAYDIUM,69KDRLYP5DTRKPHRAASZAQBWMAWZF9GUKJZFZMXZCBAS':
    '/currencies/usa,raydium,69kdrlyp5dtrkphraaszaqbwmawzf9gukjzfzmxzcbas.png',
  USBT: '/currencies/usbt.png',
  'USEDCAR,RAYDIUM,9GWTEGFJJERDPWJKJPFLR2G2ZRE3NL1V5ZPWBTSK3C6P':
    '/currencies/usedcar,raydium,9gwtegfjjerdpwjkjpflr2g2zre3nl1v5zpwbtsk3c6p.png',
  VAI: '/currencies/vai.png',
  VARA: '/currencies/vara.png',
  VC: '/currencies/vc.png',
  VELAR: '/currencies/velar.png',
  'VEMP,UNISWAP_V3,0XCFEB09C3C5F0F78AD72166D55F9E6E9A60E96EEC':
    '/currencies/vemp,uniswap_v3,0xcfeb09c3c5f0f78ad72166d55f9e6e9a60e96eec.png',
  VERSE: '/currencies/verse.png',
  VGX: '/currencies/vgx.png',
  VIB: '/currencies/vib.png',
  VISTA: '/currencies/vista.png',
  VITE: '/currencies/vite.png',
  VPR: '/currencies/vpr.png',
  'VSG,UNISWAP_V3,0X58AEA10748A00D1781D6651F9D78A414EA32CA46':
    '/currencies/vsg,uniswap_v3,0x58aea10748a00d1781d6651f9d78a414ea32ca46.png',
  'WAFFLES,RAYDIUM,8DOS8NZMGVZEAACXALKBK5FZTW4UUORP4YT8NEAXFDMB':
    '/currencies/waffles,raydium,8dos8nzmgvzeaacxalkbk5fztw4uuorp4yt8neaxfdmb.png',
  'WALTER,RAYDIUM,FV56CMR7FHEYPKYMKFMVIKV48UPO51TI9KAXSSQQTDLU':
    '/currencies/walter,raydium,fv56cmr7fheypkymkfmvikv48upo51ti9kaxssqqtdlu.png',
  'WAM,RAYDIUM,7HDEO5QCIUF8S2VFSX6URJKDNVADBU3DDCXW4ZJDCMIN':
    '/currencies/wam,raydium,7hdeo5qciuf8s2vfsx6urjkdnvadbu3ddcxw4zjdcmin.png',
  WAMPL: '/currencies/wampl.png',
  WATER: '/currencies/water.png',
  WBETH: '/currencies/wbeth.png',
  WBT: '/currencies/wbt.png',
  WCFG: '/currencies/wcfg.png',
  'WDOG,RAYDIUM,GYKMDFCUMZVRQFCH1G579BGJUZSRIJJ3LBUWV79RPUMP':
    '/currencies/wdog,raydium,gykmdfcumzvrqfch1g579bgjuzsrijj3lbuwv79rpump.png',
  'WETH,UNISWAP_V3,0XC02AAA39B223FE8D0A0E5C4F27EAD9083C756CC2':
    '/currencies/weth,uniswap_v3,0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2.png',
  'WHALES,RAYDIUM,GTH3WG3NERJWCF7VGCOXEXKGXSHVYHX5GTATEEM5JAS1':
    '/currencies/whales,raydium,gth3wg3nerjwcf7vgcoxexkgxshvyhx5gtateem5jas1.png',
  WHY: '/currencies/why.png',
  WING: '/currencies/wing.png',
  WLTH: '/currencies/wlth.png',
  'WMT,UNISWAP_V3,0X263B6B028F3E4ED8C4329EB2B5F409EE38D97296':
    '/currencies/wmt,uniswap_v3,0x263b6b028f3e4ed8c4329eb2b5f409ee38d97296.png',
  WNCG: '/currencies/wncg.png',
  'WOLF,UNISWAP_V3,0X67466BE17DF832165F8C80A5A120CCC652BD7E69':
    '/currencies/wolf,uniswap_v3,0x67466be17df832165f8c80a5a120ccc652bd7e69.png',
  'WSTETH,UNISWAP_V3,0X7F39C581F595B53C5CB19BD0B3F8DA6C935E2CA0':
    '/currencies/wsteth,uniswap_v3,0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0.png',
  WSTUSDT: '/currencies/wstusdt.png',
  X: '/currencies/x.png',
  XAR: '/currencies/xar.png',
  'XB,RAYDIUM,2UAUGWYH22SJJTATQMJ2AGEL2RBDIRKKUAK2QCCSAFCA':
    '/currencies/xb,raydium,2uaugwyh22sjjtatqmj2agel2rbdirkkuak2qccsafca.png',
  XCHNG: '/currencies/xchng.png',
  XDB: '/currencies/xdb.png',
  XSWAP: '/currencies/xswap.png',
  XVS: '/currencies/xvs.png',
  'XYO,UNISWAP_V3,0X55296F69F40EA6D20E478533C15A6B08B654E758':
    '/currencies/xyo,uniswap_v3,0x55296f69f40ea6d20e478533c15a6b08b654e758.png',
  YFII: '/currencies/yfii.png',
  'YOUNES,RAYDIUM,ANAUIZ2JJRVNTYW8CD7USQ4LRWB1PTGHYRGMWPXTPUMP':
    '/currencies/younes,raydium,anauiz2jjrvntyw8cd7usq4lrwb1ptghyrgmwpxtpump.png',
  'ZACK,RAYDIUM,8VCAUBXEJDTAXN6JNX5UAQTYTZLMXALG9U1BVFCAJTX7':
    '/currencies/zack,raydium,8vcaubxejdtaxn6jnx5uaqtytzlmxalg9u1bvfcajtx7.png',
  ZAM: '/currencies/zam.png',
  'ZAP,RAYDIUM,HXPOEHMT1VKEQJKCEPCQTJ6YYGN6XQQ1FKTY3PJX4YRX':
    '/currencies/zap,raydium,hxpoehmt1vkeqjkcepcqtj6yygn6xqq1fkty3pjx4yrx.png',
  ZAR: '/currencies/zar.png',
  ZBU: '/currencies/zbu.png',
  'ZERO,RAYDIUM,93RC484OMK5T9H89RZT5QIAXKHGP9JSCXFFFRIHNBE57':
    '/currencies/zero,raydium,93rc484omk5t9h89rzt5qiaxkhgp9jscxfffrihnbe57.png',
  ZKP: '/currencies/zkp.png',
  ZTX: '/currencies/ztx.png',
} as const;

const Placeholder = ({ className, symbol }: { className?: string; symbol: string }) => (
  <$Placeholder className={className}>
    <span>{symbol[0]}</span>
  </$Placeholder>
);

const isAssetSymbol = (symbol: Nullable<string>): symbol is AssetSymbol =>
  symbol != null && Object.hasOwn(assetIcons, symbol);

export const AssetIcon = ({
  logoUrl,
  symbol,
  className,
}: {
  logoUrl?: string;
  symbol?: Nullable<string>;
  className?: string;
}) =>
  logoUrl ? (
    <img
      src={logoUrl}
      className={className}
      alt={symbol ?? 'logo'}
      tw="h-[1em] w-auto rounded-[50%]"
    />
  ) : isAssetSymbol(symbol) ? (
    <$AssetIcon src={assetIcons[symbol]} className={className} alt={symbol} />
  ) : (
    <Placeholder className={className} symbol={symbol ?? ''} />
  );

const $AssetIcon = styled.img`
  --asset-icon-size: 1em;

  height: var(--asset-icon-size);
  min-height: var(--asset-icon-size);
  width: var(--asset-icon-size);
  min-width: var(--asset-icon-size);

  border-radius: 50%;
`;

const $Placeholder = styled.div`
  --asset-icon-size: 1em;

  height: var(--asset-icon-size);
  min-height: var(--asset-icon-size);
  width: var(--asset-icon-size);
  min-width: var(--asset-icon-size);

  background-color: var(--color-layer-5);
  border-radius: 50%;
  overflow: hidden;

  span {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    font-size: 0.5em;
  }
`;
