---
config:
  theme: redux-dark-color
  layout: elk
title: Starboard Entity Relationship Diagram
---
erDiagram
	direction TB
  ADDRESS {
    string address
  }

  ADDRESS ||--o{ SUBACCOUNT : has

  SUBACCOUNT {
    string address
    int    subaccount_number
    string subaccount_id
  }

  MARKET {
    string ticker
    string market_type
  }


  PERPETUAL_POSITION {
    string id
    string subaccount_id
    string ticker
    string status
    string created_at
    string created_height
  }
    SUBACCOUNT ||--o{ PERPETUAL_POSITION : owns
      MARKET ||--o{ PERPETUAL_POSITION : for

%%   ASSET_POSITION {
%%     string id
%%     string subaccount_id
%%     string asset_symbol
%%     string status
%%     string created_at
%%     string created_height
%%   }
%%     SUBACCOUNT ||--o{ ASSET_POSITION : owns

  ORDER {
    string order_id 
    string subaccount_id
    string ticker
    string side
    string status
    string type
    string good_til_block
    string good_til_time
    string created_at
  }

  SUBACCOUNT ||--o{ ORDER : places
    MARKET ||--o{ ORDER : on

  FILL {
    string fill_id 
    string order_id
    string subaccount_id
    string ticker
    string executed_at
    string executed_height
  }
      SUBACCOUNT ||--o{ FILL : executes
    ORDER ||--o{ FILL : generates
  MARKET ||--o{ FILL : on

  TRANSFER {
    string transfer_id 
    string source_subaccount_id
    string recipient_subaccount_id
    string created_at
    string created_height
  }
    SUBACCOUNT ||--o{ TRANSFER : as_source
  SUBACCOUNT ||--o{ TRANSFER : as_recipient

  PNL_TICK {
    string id 
    string subaccount_id
    string effective_at
    string created_height
  }
    SUBACCOUNT ||--o{ PNL_TICK : produces

%%   REWARD {
%%     string id
%%     string address
%%     string block_time
%%     string block_height
%%   }
%%  ADDRESS ||--o{ REWARD : earns

  CANDLE {
    string id 
    string ticker
    string interval
    string open_time
  }

  MARKET ||--o{ CANDLE : aggregates

  TRADE {
    string trade_id 
    string ticker
    string executed_at
  }
    MARKET ||--o{ TRADE : trades

  FUNDING_PAYMENT {
    string id 
    string ticker
    string effective_at
  }
  MARKET ||--o{ FUNDING_PAYMENT : applies_to


  FUNDING_RATE {
    string id 
    string ticker
    string effective_at
  }
  MARKET ||--o{ FUNDING_RATE : history
