name: Lint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up pnpm
        uses: dydxprotocol/setup-pnpm@3bcbd1d6c86dd1b0bce6d5309bf19fb95282f8ac # v2.0.0

      - name: Set up Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install @commitlint/config-conventional

      - name: Lint PR Title
        run: |
          echo "${PR_TITLE}" | pnpx commitlint --config commitlint.config.ts
        env:
          PR_TITLE: '${{ github.event.pull_request.title }}'

      - name: ESLint
        run: |
          pnpm lint
